### ISSUE TITLE
Add Changelog?

### ISSUE THREAD

**Issue by crccheck** [siimon/prom-client#104]
There have been two major releases recently, but I can't tell what's changed.

**Comment by SimenB** [comment]
There aren't _too_ many changes, but I agree a changelog would be good.
You can do https://github.com/siimon/prom-client/compare/v7.0.0...v8.0.0 and for 8->9 and look at the readme, that usually works :smile:

**Comment by crccheck** [comment]
Something I've done in the past is include the https://github.com/siimon/prom-client/compare/v7.0.0...v8.0.0 link in the https://github.com/siimon/prom-client/releases page for each release.

**Comment by SimenB** [comment]
Creating a changelog following www.keepachangelog.com and using something like chandler to push it to releases works great as well.

**Comment by crccheck** [comment]
whoa, thanks for the info about Chandler. That looks like a nice tool. I've been using https://github.com/rvagg/changelog-maker and then editing the output by hand too.

**Comment by siimon** [comment]
Good idea, I'll create a change log file and update it accordingly in the future!
