### ISSUE TITLE
nock is broken in node 8 - causing tests to fail

### ISSUE THREAD

**Issue by siimon** [siimon/prom-client#112]
I'll let the test be activated for now and let the nock contributors have some time to fix it. If something doesn't happens soon we'll have to rewrite the tests fixtures to something else.

There are a couple of issues for this
https://github.com/node-nock/nock/issues/925
https://github.com/node-nock/nock/issues/922
https://github.com/node-nock/nock/issues/928

**Comment by SimenB** [comment]
I'll deal with this in #126.
