### ISSUE TITLE
Is it possible to break up metrics by sub-properties?

### ISSUE THREAD

**Issue by jackspaniel** [siimon/prom-client#113]
Basically we are trying to match some Prometheus output that's generated by Java apps, with our node apps - so they can be scraped by the same algorithm. 

Here is what the Java output looks like for a couple of end points:

```
# HELP app_request_latency Latencies associated with uris of this application.
# TYPE app_request_latency summary
app_request_latency{uri="/info",quantile="0.5",} 1.0
app_request_latency{uri="/info",quantile="0.95",} 2.0
app_request_latency_count{uri="/info",} 101909.0
app_request_latency_sum{uri="/info",} 130389.0
app_request_latency{uri="/health",quantile="0.5",} NaN
app_request_latency{uri="/health",quantile="0.95",} NaN
app_request_latency_count{uri="/health",} 97.0
app_request_latency_sum{uri="/health",} 253772.0
```

And here is the best I've been able to do with the node output:

```
# HELP app_request_latency_info /info
# TYPE app_request_latency_info summary
app_request_latency_info{quantile="0.5"} 4
app_request_latency_info{quantile="0.95"} 4
app_request_latency_info_sum 5
app_request_latency_info_count 2
# HELP app_request_latency_health /health
# TYPE app_request_latency_health summary
app_request_latency_health{quantile="0.5"} 2
app_request_latency_health{quantile="0.95"} 2
app_request_latency_health_sum 3
app_request_latency_health_count 2
```

As you can see I'm using the metric name to separate them. So it's not really broken down the way we need to match the Java output (by a uri property). I don't know right now if they did some crazy custom work to get that. I'm just wondering if there's some easy way to replicate it with the node client.

**Comment by siimon** [comment]
Couldn't you just add the label uri in prom-client?

**Comment by jackspaniel** [comment]
Yes. Labels is what I needed. Somehow I missed that in the readme. 

Although FYI it seems to work a bit different for Summary than for the Gauge example:

```
gauge.labels('GET', '200').set(100); // 2nd version, Same as above
```

For summary I found this works:

```
Prometheus.metricsMap[name].labels(path).observe(took);
```

So just the label value and not the name. Otherwise I get an invalid # of arguments error.
