### ISSUE TITLE
nodejs_version_info not working with timestamp

### ISSUE THREAD

**Issue by sgulseth** [siimon/prom-client#114]
Since the timestamp for `nodejs_version_info` is stale it looks like prometheus stops scraping the metric after a short while, and therefor the data does not appear when querying for it.

![screenshot 2017-06-16 15 34 27](https://user-images.githubusercontent.com/1627633/27228792-4b93a53c-52a9-11e7-96d6-96264e04e587.png)

**Comment by SimenB** [comment]
Should remove timestamp from all the metrics that are set once.

I'd guess `nodejs_version_info`, `process_start_time_seconds`, `process_max_fds` should have timestamp removed.
