### ISSUE TITLE
Drop support for node older than 4

### ISSUE THREAD

**Issue by SimenB** [siimon/prom-client#116]
Would allow us to use classes instead of prototype, and easier handling of `this`. We just test on node 4, 6 and 8 on CI now anyways. If you're interested @siimon, I can make a PR for it.

**Comment by siimon** [comment]
Yeah the support is kind of dropped already, think there are some Object.assign that's not supported in older versions!

**Comment by SimenB** [comment]
Oh, the pushgateway uses object assign. Oops. Should we roll with it, or add a dep on `object-assign` roll a 9.2.2, then remove it again for a 10.0.0 with other changes?

**Comment by SimenB** [comment]
Breaking changes I can think of: `class`, arrow functions, `Object.assign` and removing support for non-object instantiation of metrics. And maybe something like https://github.com/siimon/prom-client/issues/83#issuecomment-289441524.

Other things?

**Comment by siimon** [comment]
No, the support is dropped, wasn't by mistake 🙂so there is nothing that stops from using classes instead

**Comment by SimenB** [comment]
Cool! Will send a PR for syntactic changes then, and wait for others

**Comment by siimon** [comment]
Just looked at the log, support was dropped in 7.0.0!

**Comment by SimenB** [comment]
See #117

**Comment by SimenB** [comment]
PRs open, gonna close this
