### ISSUE TITLE
How to use with Koa?

### ISSUE THREAD

**Issue by montanaflynn** [siimon/prom-client#138]
I see the example is for express.js but I would like to use it with [Koa](https://github.com/koajs/koa), basically we just want to monitor open file descriptors (it will be hosted on linux) using prometheus. 

The docs say:

> See example folder for a sample usage. The library does not bundle any web framework, to expose the metrics just return the metrics() function in the registry.

Which I find confusing especially combined with the example which has a `globalRegistry` on [line #5](https://github.com/siimon/prom-client/blob/master/example/server.js#L5)

**Comment by siimon** [comment]
I've not used Koa myself, but it should just be to create a route on /metrics and expose the metrics in the registry (assuming you register all metrics on the globalRegistry which is default).

The example could probably be better and not use the internal prom-client globalRegistry property. You could use the register property instead like this

```javascript
   const register = require('prom-client').register;
   console.log(register.metrics()); //Instead of console log, return this as the response in the http request
```

**Comment by montanaflynn** [comment]
I don't get any output from running `register.metrics()`

```js
const register = require('prom-client').register;

setInterval(function(){
    console.log(register.metrics());
}, 1000)
```

**Comment by SimenB** [comment]
You have to register some metrics. You can use the default ones.

```js
const { register, collectDefaultMetrics } = require('prom-client');

collectDefaultMetrics();

setInterval(function(){
    console.log(register.metrics());
}, 1000);

**Comment by SimenB** [comment]
>The example could probably be better and not use the internal prom-client globalRegistry property.

b4e9be54dc5d1172c78591d095495857c441b7b5

**Comment by montanaflynn** [comment]
@siimon and @SimenB thanks so much I got it working!

```js
let app = require('koa')();
let router = require('koa-router')();

const { register, collectDefaultMetrics } = require('prom-client');

collectDefaultMetrics();

router.get('/', function *(next) {
    yield next;
    this.body = "hello world";
});

router.get('/metrics', function *(next) {
    yield next;
    this.body = register.metrics();
});

app.use(router.routes());
app.use(router.allowedMethods());

app.listen(3000);
console.log('listening on port 3000');
```
