### ISSUE TITLE
High CPU usage since 9 version

### ISSUE THREAD

**Issue by SkeLLLa** [siimon/prom-client#140]
Hi. I've noticed high CPU usage by prom-client since version 9 (10 also affected). Version 8 works fine.

Code is pretty simple:
```js
const client = require('prom-client');
client.collectDefaultMetrics({ timeout: 1000 });
```

With default metrics enabled app eats ~60% of CPU. Without - ~0.1%. Node version 8.1.X.
If I have some time to look, I'll provide some additional info.

UPD:
It seems that problem is somewhere in general code, not specific metric, because even "version" metric eats 6-8% CPU. If I enable more metrics, it eats CPU proportionally.

**Comment by SimenB** [comment]
Oh, that's interesting. The only thing that really changed is timestamp support (#69 and #103). Other than that, just how metrics are constructed and ability to merge them, neither of which should impact runtime performance.

Do you see the same thing with metrics without timestamps? Or if you remove timestamp support entirely?

**Comment by SimenB** [comment]
Diff: https://github.com/siimon/prom-client/compare/v8.1.1...v9.0.0

**Comment by SimenB** [comment]
Just removing timestamp from the default metrics made no difference

**Comment by SkeLLLa** [comment]
@SimenB I've run with CPU profile and it shown that most of time it spends in "idle" state (aka `(program)`), so nothing unusual. It shouldn't eat so much CPU.

**Comment by SimenB** [comment]
hmm, I just see the issue on v10, not v9.


sup.js:

```js
require('.').collectDefaultMetrics()

// Keep process alive
setInterval(() => {}, 1000)
```

Then `git checkout v9.1.1 && node sup.js` in one terminal, and `git checkout v10.0.0 && node sup.js` in the other.

![image](https://user-images.githubusercontent.com/1404810/27958503-aec6253c-6323-11e7-9ba5-aa1763a51849.png)

Top one is v10

**Comment by SkeLLLa** [comment]
@SimenB for me it reproduces on both: ^9.0.0 and ^10.0.0

**Comment by SimenB** [comment]
Running on node@8 puts v10 at 12% instead of 16%, but v9.1.1 stays at the same (0.1%).

> @SimenB for me it reproduces on both: ^9.0.0 and ^10.0.0

Odd!

**Comment by SkeLLLa** [comment]
Here's CPU chart. 9 is on the left, 8 on the right:
http://i.imgur.com/0ypaho2.png

**Comment by SimenB** [comment]
v10 `--prof` output

```
 [Shared libraries]:
   ticks  total  nonlib   name
   5060   89.8%          /usr/lib/system/libsystem_kernel.dylib
      7    0.1%          /usr/lib/system/libsystem_pthread.dylib
      6    0.1%          /usr/lib/system/libsystem_c.dylib
      5    0.1%          /usr/lib/system/libsystem_platform.dylib
      1    0.0%          /usr/lib/system/libsystem_malloc.dylib
```

v9

```
 [Shared libraries]:
   ticks  total  nonlib   name
     12   12.9%          /usr/lib/system/libsystem_kernel.dylib
      2    2.2%          /usr/lib/system/libsystem_pthread.dylib
      2    2.2%          /usr/lib/system/libsystem_platform.dylib
      1    1.1%          /usr/lib/system/libsystem_malloc.dylib
      1    1.1%          /usr/lib/system/libsystem_c.dylib
```

**Comment by SimenB** [comment]
Weird that we're getting different results...

This commit is what drove cpu usage through the roof on my machine: https://github.com/siimon/prom-client/commit/c8a32d920ca459e44a8a1a37ab5fbd6471739ad9

**Comment by SkeLLLa** [comment]
Probably that's because I use linux :).

v9 results:
```
 [Shared libraries]:
   ticks  total  nonlib   name
    298    3.2%          /usr/bin/node
    254    2.7%          /lib64/libpthread-2.23.so
    115    1.2%          /lib64/libc-2.23.so
     10    0.1%          [vdso]
      9    0.1%          /usr/lib64/libuv.so.1.0.0
      6    0.1%          /usr/lib64/gcc/x86_64-pc-linux-gnu/5.3.0/libstdc++.so.6.0.21
```

**Comment by SimenB** [comment]
I don't get JavaScript. The diff fixing the crazy CPU usage for is this


```diff
diff --git i/lib/defaultMetrics.js w/lib/defaultMetrics.js
index 077ce2f..cd737bd 100644
--- i/lib/defaultMetrics.js
+++ w/lib/defaultMetrics.js
@@ -69,7 +69,7 @@ module.exports = function startDefaultMetrics(config) {
 
 	existingInterval = setInterval(
 		updateAllMetrics,
-		normalizedConfig.interval
+		10000
 	).unref();
 
 	init = false;
```

**Comment by SkeLLLa** [comment]
@SimenB 
```
normalizedConfig.interval
```
doesn't equal 
```
normalizedConfig.timeout
```
:)

**Comment by SimenB** [comment]
Oh, hahaha. So we passed `undefined`....

**Comment by SimenB** [comment]
Well, then... 10.0.2 published! Thanks for spotting it. /cc @siimon

But that still leaves your issue, @SkeLLLa. I can't reproduce on v9. Do you have a script I could run to test it? Which OS are you on?

**Comment by SimenB** [comment]
Are you able to bisect which commit causes the issue?

**Comment by SkeLLLa** [comment]
My code is in the first comment :). Just add setTimeout or setInterval to prevent node process to exit.

**Comment by SkeLLLa** [comment]
@SimenB With 9 version - it just my bad, because I used code from v10 with v9. So in v9 it received object instead of number for `interval`.

**Comment by SimenB** [comment]
Oh, so v10.0.2 fixed the problem?

**Comment by SimenB** [comment]
If not, I've created this Dockerfile and I'm ready to start bisecting

```Dockerfile
FROM node:8

USER node

WORKDIR /home/node

RUN git clone https://github.com/siimon/prom-client.git

WORKDIR /home/node/prom-client

RUN git checkout v8.0.0

RUN npm install --only=production

RUN echo "var m = require('./');\nm.collectDefaultMetrics && m.collectDefaultMetrics();\n\nsetInterval(() => console.log(m.register.metrics()), 1000);\n" > testFile.js

CMD ["bash"]
```

**Comment by SkeLLLa** [comment]
@SimenB 10.0.2 is fine.

**Comment by SimenB** [comment]
Perfect, thanks for pointing it out!
