### ISSUE TITLE
System is giving error of value is not a valid number

### ISSUE THREAD

**Issue by abhay40711cs** [siimon/prom-client#150]
While calling Historgram i am getting issue of Value is not valid number 
'Created the below object : 

const httpRequestDurationMicroseconds = new client.Histogram({
  name: 'http_request_duration_ms',
  help: 'Duration of HTTP requests in ms',
  buckets: [0.10, 5, 15, 50, 100, 200, 300, 400, 500]  // buckets for response time from 0.1ms to 500ms
})
 

Implementing "-

app.use((req, res, next) => {
console.log("Inside responseTimeInMs");  
const responseTimeInMs = Date.now() - res.locals.startEpoch

console.log(responseTimeInMs);  

	if(req.path!=undefined) {
			console.log("Calling httpRequestDurationMicroseconds");
			httpRequestDurationMicroseconds.observe(responseTimeInMs)
	}
  next()
});

Error: Value is not a valid number
    at D:\Test_abhay\deploy\orcadWEB\orWebApplicationServer\orWebApplicationServer\node_modules\prom-client\lib\histogram.js:229:10
    at Histogram.observe (D:\Test_abhay\deploy\orcadWEB\orWebApplicationServer\orWebApplicationServer\node_modules\prom-client\lib\histogram.js:103:54)

**Comment by SimenB** [comment]
Are you sure `res.locals.startEpoch` is a number?

There is an open PR to actually print the value being rejected (#149), but in the meantime, what is the value of `responseTimeInMs` at invocation?
