### ISSUE TITLE
Unusual ask; call set on a Counter? or alternate solution?

### ISSUE THREAD

**Issue by vidhill** [siimon/prom-client#151]
I am using prom-client in a bit of an unusual way, 

We are receiving statistics from a service (via mqtt messages), 
to make these metrics available to prometheus I am using prom-client...

Right now I am publishing all stats using instances of `Gauge`

Some of the metrics are 'max' values, i.e. they are the max recorded figures, so strictly speaking they should really be instances of `Counter` instead of `Gauge`
 

however as the values are pre-recorded before I receive them I would need to be able to call `myCounter.set(val)` on an instance of a Counter

Or maybe there is a better way of doing this?

Thanks

**Comment by vidhill** [comment]
I have thought of a solution that would probably work, 

but, it'd probably be a little messy, I could use a `Counter`, 
when I would receive an update to the statistic I could get the current value of the Counter, and call `myCounter.inc(num);` with the right number to bring the value up to right figure...


-it feels a little messy though..

**Comment by siimon** [comment]
> Some of the metrics are 'max' values, i.e. they are the max recorded figures, so strictly speaking they should really be instances of Counter instead of Gauge

What makes you think that? In my world that seems like a perfect fit for a Gauge? I would recommend reading the [metric guidelines](https://prometheus.io/docs/concepts/metric_types/)!

**Comment by vidhill** [comment]
It's the bit that says 
> A counter is a cumulative metric that represents a single numerical value that only ever goes up.

A sample metric I am receiving is  max_connected_clients as in the max number ever..
It only resets to zero when the application restarts

**Comment by SimenB** [comment]
I'm gonna close this since it's not actionable for us, but feel free to keep discussing!

>It only resets to zero when the application restarts

That's the exact behavior of a counter.
