### ISSUE TITLE
how to calculate cpu usage from `process_cpu_*`

### ISSUE THREAD

**Issue by portenez** [siimon/prom-client#152]
How can I generate cpu usage based on the default metrics `process_cpu*`?

Right now I'm using `irate(process_cpu_seconds_total[2m])` but while running load test to verify this metric, I only see this going to 0.5 when I know that we're pretty much at 100%. 

Can anyone provide some guidance?

**Comment by SimenB** [comment]
That's time spent on the cpu, it has no correlation with load
