### ISSUE TITLE
counters creates an extra entry when not using labels

### ISSUE THREAD

**Issue by jramoyo** [siimon/prom-client#156]
when a counter is constructed without labels, the hashmap is initialised as:
```js
if (this.labelNames.length === 0) {
  this.hashMap = createValue({}, 0);
}
```

this creates a map entry with a key of `undefined`

however when `inc` is called with empty labels (`counter.inc({}, 1)`), it creates an entry with an empty string as the key (due to the hash function).

```js
if (!isObject(labels)) {
  return inc.call(this, null)(labels, value);
}

const hash = hashObject(labels); // {} is a valid object, hashObject returns ''
return inc.call(this, labels, hash)(value, timestamp);
```

eventually resulting to the following metric:

```json
  {
    "help": "my_counter",
    "name": "my_counter",
    "type": "counter",
    "values": [
      {
        "value": 0,
        "labels": {}
      },
      {
        "value": 2,
        "labels": {}
      }
    ],
    "aggregator": "sum"
  }
```

**Comment by SimenB** [comment]
Huh, that's weird behavior! Would you mind sending a PR to fix it?

**Comment by jramoyo** [comment]
pull request: https://github.com/siimon/prom-client/pull/158
