### ISSUE TITLE
object-hash dependency introduces high CPU overhead

### ISSUE THREAD

**Issue by amp001** [siimon/prom-client#16]
While load-testing, we noticed unusually high CPU usage in one of our services and tracked it down to calling prom-client counters. On further investigation, the culprit appears to be calls to the objectHash() function from the object-hash module prom-client depends on. That function, in turn, does quite a bit, including talking to the native crypto libraries to figure out what algorithms are available, instantiating one of them, dispatching to a type-specific handler (which, in the case of an object, recursively flattens the object so it can feed it to one of the cryptographic hash algorithms). On my older Core i7 machine, I could only manage to call counter.inc() about 3,000 times per second at 85% CPU utilization while doing absolutely no other work. Given this level of overhead, we cannot use prom-client in its current state.

So, I rewrote the hashObject() function in prom-client's lib/util.js to do the bare minimum amount of work necessary to produce a unique (and cross-call consistent) string since it doesn't actually need to be a hash – it's only ever used as a key. Now, I can do 300,000 calls to counter.inc() per second while using 85% CPU. This is with a labels object that has two keys in it. An empty labels object can handle 300,000 calls per second at 35% CPU.

Based on those encouraging results, I went through the rest of the prom-client code this morning and made the rest of the changes to eliminate the dependency on object-hash entirely by having the other modules call the updated hashObject() function in lib/util.js. "npm test" works – all tests pass. Patch attached.

[objectHash.diff.txt](https://github.com/siimon/prom-client/files/255127/objectHash.diff.txt)

**Comment by siimon** [comment]
Awesome! Could you create a PR with your patch?

**Comment by amp001** [comment]
Sure. I'm relatively new to Github – is that a "Pull Request"? Give me some time to figure out how to do that...

**Comment by amp001** [comment]
Ok, I _think_ I have a pull request created properly with this patch. Let me know if I did it wrong.

**Comment by siimon** [comment]
Yes, just merged it, will publish to npm during the day! 

Thanks for you contribution!
