### ISSUE TITLE
Setting initial values for metrics is recommended

### ISSUE THREAD

**Issue by swapsCAPS** [siimon/prom-client#161]
https://www.robustperception.io/existential-issues-with-metrics/

Should we let prom-client do this, or should we let the user do this manually?
I would imagine we would need the user to set the initial value for a gauge.
As the user needs to know if the gauge has the initial state or if it has been set by the program.
Letting prom-client set default values might be misleading. Optional constructor argument maybe?
Counters can be set to 0 at program start I guess.
Any thoughts? I might be able to work on this.

Cheers

edit:
Hmm an immediate issue that crops up is how to do this for multiple labels
This will mean the user has to specify all of the labels on init. Meh.
Only then can we set each of the counters to 0 right?
Then it'll be easier to just have the user inc() the counters with value 0 manually?

**Comment by SimenB** [comment]
See #139

We do initialize metrics without labels. As you noted, not real way of doing it when there are labels.

**Comment by SimenB** [comment]
This mimics the official java client. If you think there's some way this can be solved generally, please take it up on the prometheus discussion board, and if it lands, we can make the change here afterwards.

https://groups.google.com/forum/#!forum/prometheus-users
