### ISSUE TITLE
How to run with Pm2 module?

### ISSUE THREAD

**Issue by fmr683** [siimon/prom-client#165]
If I"m running with pm2 module where should I put this code https://github.com/siimon/prom-client/blob/master/example/cluster.js ? or is it necessary?

**Comment by zbjornson** [comment]
It looks like pm2 doesn't let you run your own code in the master process. Without the ability to do that, you'll be getting metrics from a single worker, which will be incorrect (partial) data if you're using multiple workers.

**Comment by siimon** [comment]
Seems to be answered so I'm closing this one

**Comment by ChrisLahaye** [comment]
I created a library for this purpose and provide an example for usage with prom-client.

See https://github.com/ChrisLahaye/pm2-messages
