### ISSUE TITLE
Timestamps should be in seconds, eg in setToCurrentTime methods

### ISSUE THREAD

**Issue by kamalmarhubi** [siimon/prom-client#167]
The [implementation of setToCurrentTime](https://github.com/siimon/prom-client/blob/ee4c09322f6ffa3785b18a24cca6be4516f40140/lib/gauge.js#L170-L179) for gauges uses the value of `Date.now()` which is in milliseconds. The suggested conventions for client libraries is to use base units for all recorded metrics.

**Comment by SimenB** [comment]
Very good point. Mind sending a PR for it? It's a breaking change, but that's fine. It will match the java client: https://github.com/prometheus/client_java/blob/1a8bf7da57402f444861c32abc9e0c7cd313748e/simpleclient/src/main/java/io/prometheus/client/Gauge.java#L178-L180

**Comment by siimon** [comment]
Oh that one slipped under the radar! If you create a PR don't forget the change log :)

**Comment by kamalmarhubi** [comment]
This can be done without breakage by adding a default-true flag `legacyCurrentTimeMilliseconds` on gauges. The flag can be set to false by people like me who want seconds. A breaking change can flip the default, and a further one can remove it.

I will probably PR this soon.

**Comment by siimon** [comment]
I'm leaning towards making the breaking change right away instead of starting to add legacy properties, what do you think @SimenB ?

**Comment by kamalmarhubi** [comment]
Happy to do either! :-)
