### ISSUE TITLE
Metrics should allow NaN as a value

### ISSUE THREAD

**Issue by kamalmarhubi** [siimon/prom-client#168]
This is particularly true for gauges. If I want to [avoid missing metrics](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics), and 0 is a meaningful value, I need to set the gauge to NaN, but the [current implementation disallows this](https://github.com/siimon/prom-client/blob/ee4c09322f6ffa3785b18a24cca6be4516f40140/lib/gauge.js#L218-L220).

**Comment by SimenB** [comment]
Good point! Can you send a PR for it?

**Comment by kamalmarhubi** [comment]
Yup will do!

**Comment by brian-brazil** [comment]
While NaN should be supported as a gauge value, using it in this way is inadvisable. NaN should only be used where it makes mathematical sense, not as a form of "missing" value.
