### ISSUE TITLE
Express middleware implementation wanted?

### ISSUE THREAD

**Issue by DonMartin76** [siimon/prom-client#172]
I just wanted to ask a short question whether a PR which adds an Express middleware to this library is something you would consider merging?

Something like this: https://gist.github.com/DonMartin76/24ec7f33fd63ad94cd24f8b8adad3b54

It does **not** pull in Express as a dependency, but just introspects a little and derives automatic histograms and statistics from the Express routes.

If you say this is kind of interesting, I'd see how it could fit in to the library and file a pull request. If not, I'd perhaps create an npm library on my own. But I think it might fit in here as well, as a time saver for a (supposedly) very common use case of `prom-client`.

Thank you for your work!

**Comment by SimenB** [comment]
I don't think it needs to live in this repo - mostly to not tie potential breaking changes in the middleware to breaking changes in the main module.

I think linking to a repo containing the middleware would be great though! We have one at work as well - being able to drop that would be awesome 🙂

**Comment by SimenB** [comment]
There is https://github.com/jochen-schweizer/express-prom-bundle already, fwiw

**Comment by DonMartin76** [comment]
Oh wow, thanks for that link! Closing this for now then, thanks for your feedback! Will check out jochen-schweizer and possibly also drop our own.
