### ISSUE TITLE
startTimer can mutate passed-in startLabels object

### ISSUE THREAD

**Issue by kdk** [siimon/prom-client#176]
Hi! Thanks for the great library!

The `startTimer` utility functions are super useful, but can lead to confusing behavior if the client holds on to a reference to the object provided in `startLabels`, since it will be mutated (with `endLabels`) when the function to stop the timer is executed.

Example:
```
let metricLabels = { action: 'action' };
let stopTimer = time.startTimer(metricLabels);
...
stopTimer({ errorCode: 1 });
counter.inc(metricLabels);
```
`counter` is recorded with labels of `{ action: 'action', errorCode: 1 }`.

Possible fix:
In `startTimer` in lib/histogram.js and lib/summary.js, replace
```
this.observe(
	Object.assign(startLabels || {}, endLabels),
	delta[0] + delta[1] / 1e9
);
```
with
```
this.observe(
	Object.assign({}, startLabels, endLabels),
	delta[0] + delta[1] / 1e9
);
```
This probably incurs a small performance cost.

**Comment by siimon** [comment]
Good catch! A PR is welcome 😊
