### ISSUE TITLE
De-emphasise resetting metrics to avoid confusion

### ISSUE THREAD

**Issue by brian-brazil** [siimon/prom-client#179]
The main readme mentioned resetting metrics in several places. While there are rare valid use cases for this involving unittesting, most users get confused by this and think they need to reset at every scrape or have other misunderstandings. I'd suggest not mentioning this functionality.

**Comment by SimenB** [comment]
Yeah, I've never used it myself. I have cleared all metrics for testing purposes, but I've never cleared a metric.

👍 for removing its mention from the readme (at least from every single metric type).

**Comment by zbjornson** [comment]
Fixed in #243 🎉
