### ISSUE TITLE
Counter needs set() function or reset() with labels support

### ISSUE THREAD

**Issue by PatrLind** [siimon/prom-client#192]
I am counting things in my app like the number of SQL queries performed etc. Because of a modular design the SQL module is counting the number of queries internally. My metrics module is the collecting these numbers on a update interval and sets the prom-client counters to that value.

Because a prom-client counter does not have a set() function I have to call reset() every time I want to call inc() with the new value. With the inc() function I can set values for different labels, but the reset() function does not have such a feature. This means I cannot use labels with counters if I do my own counting externally from the prom-client.

Gauges have a set() function, but this is a counter, not a gauge.

So my suggestion is to either have the reset() function support labels or implement a set() function for counters as well (it could throw an exception if the value was lower than before).
Or is it that I have overlooked something?

**Comment by siimon** [comment]
Why can't you use a gauge instead?

Actually using reset like this is an antipattern and the intended use case is mostly unit testing see #179.

**Comment by PatrLind** [comment]
However.... Now that I am reading this document [https://prometheus.io/docs/concepts/metric_types/](https://prometheus.io/docs/concepts/metric_types/) I see that the server actually doesn't seem to make a difference between a counter and a gauge. So maybe I should just do as you suggests (although it feels wrong to me).

**Comment by siimon** [comment]
I'd say this case fits the gauge use case fine, what you seems to be doing is taking a snapshot of the SQL module at a timeinterval which is one of the points with a gauge. Sure it only happens to go up I don't see any problem with that.
