### ISSUE TITLE
Running cluster mode + aggregation metrics from middleware

### ISSUE THREAD

**Issue by lfender6445** [siimon/prom-client#203]
I'd like to collect aggregate metrics via koa midlleware 

```jsx
// NOTE: app is running in cluster mode
import mount from 'koa-mount'

const AggregatorRegistry = require('prom-client').AggregatorRegistry

const registry = new AggregatorRegistry()

const metricsServer = ctx => {
  registry.clusterMetrics((err, metrics) => {
    // callback is never evaluated due to error
    if (err) console.log('Prometheus aggregation error', err)
    ctx.status = 200
    ctx.headers['content-type'] = registry.contentType
    ctx.body = metrics
  })
}

export default koaApp => {
  koaApp.use(
    mount('/metrics', metricsServer)
  )
}
```

But I get a failure here https://github.com/siimon/prom-client/blob/master/lib/cluster.js#L41

`TypeError: Cannot convert undefined or null to object` because cluster.workers is undefined - i am however running my app in cluster mode - any thoughts on why cluster.workers comes back undefined? Does the app think its running on a single thread? 

I have had success following the example that runs aggregate metrics from a standalone server w/ cluster mode  (rather than middleware) but was hoping someone could shed light on what i'm missing here. I realize this probably has more to do with how clustering works in general (rather than prom-client)

**Comment by zbjornson** [comment]
That error implies that the `AggregatorRegistry` is being setup in a worker process, whereas it can only be setup in the master process. (`cluster.workers` is undefined in workers.)

I'm not that familiar with Koa, but looking at [koajs/cluster](https://github.com/koajs/cluster), I don't see a way to run code in the master process, which is *required* for the `AggregatorRegistry` to work.

**Comment by lfender6445** [comment]
Thanks for the quick response zbjornson
