### ISSUE TITLE
Is it possible to end a histogram timer without observing the value?

### ISSUE THREAD

**Issue by Heimonen** [siimon/prom-client#209]
If I for instance want to collect metrics on successful requests, how would I do that?

```
const histogram = new Histogram({ name: 'name', help: 'help' })
try {
    const end = histogram.startTimer()
    await sendRequest(args)
    end()
} catch (error) {
    // Is this correct? Will the histogram be garbage collected?
    histogram.reset()
}
```

**Comment by SimenB** [comment]
`reset` is wrong. I think you can just never call `end`, it should be GC-ed. Or you can just use labels for success and failure state

**Comment by Heimonen** [comment]
Ok, labels is a good solution.

> I think you can just never call end, it should be GC-ed

Shouldn't it keep the timer alive until end is called?

**Comment by siimon** [comment]
The naming is maybe confusing, but it's not actually a timer that is returned, it's a regular function. So it's no difference from having a regular variable in a try and catch clause, so no, it wont leak, but @SimenB suggestions makes more sense
