### ISSUE TITLE
Scraped Histogram metrics are not reflecting actual bucket counts with version 11.1.1

### ISSUE THREAD

**Issue by cgianelle** [siimon/prom-client#212]
prom-client ver: 11.1.1

I was playing around with the Histogram and noticed something that didn't seem right as it regards the buckets counts when my service endpoint is scraped by Prometheus.

Here's my setup:
~~~~
        var scheduledDurationHistogram = new Historgram({
            name: 'tstv_test_histogram',
            help: 'test',
            labelNames: ['channel_id', 'status'],
            buckets: [0.1, 0.5, 1, 5, 10, 15]
        });

        scheduledDurationHistogram.observe({channel_id:'1', status:'ok'}, 0.7);
        scheduledDurationHistogram.observe({channel_id:'1', status:'ok'}, 1.7);
~~~~

When I query my service's Prometheus endpoint, I was expecting:
~~~~
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="0.1",channel_id="1",status="ok"} 0
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="0.5",channel_id="1",status="ok"} 0
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="1",channel_id="1",status="ok"} 1
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="5",channel_id="1",status="ok"} 1
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="10",channel_id="1",status="ok"} 0
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="15",channel_id="1",status="ok"} 0
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="+Inf",channel_id="1",status="ok"} 2
tstv_test_histogram_sum{serviceName="ivp-capture-service",channel_id="1",status="ok"} 2.4
tstv_test_histogram_count{serviceName="ivp-capture-service",channel_id="1",status="ok"} 2
~~~~

but I got the following instead:

~~~~
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="0.1",channel_id="1",status="ok"} 0
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="0.5",channel_id="1",status="ok"} 0
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="1",channel_id="1",status="ok"} 1
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="5",channel_id="1",status="ok"} 2
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="10",channel_id="1",status="ok"} 2
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="15",channel_id="1",status="ok"} 2
tstv_test_histogram_bucket{serviceName="ivp-capture-service",le="+Inf",channel_id="1",status="ok"} 2
tstv_test_histogram_sum{serviceName="ivp-capture-service",channel_id="1",status="ok"} 2.4
tstv_test_histogram_count{serviceName="ivp-capture-service",channel_id="1",status="ok"} 2
~~~~

I setup my debugger and walked through the code. When the call to _observe_ is made, my expectations are satisfied. Buckets 1 and 5 both have a single item associated with them, the overall count is 2 and the sum is 2.4. From my debugger:
<img width="740" alt="screen shot 2018-08-16 at 5 30 34 pm" src="https://user-images.githubusercontent.com/7561730/44360764-dec92880-a489-11e8-8aaf-673e1ba5f1cf.png">

The issue I'm raising, from what I saw, is in the presentation layer when I make the call to fetch the metrics from my services Prometheus endpoint. Where my expectations breakdown is when _createBucketValues_ called. 
~~~~
function createBucketValues(bucket, histogram) {
	let acc = 0;
	return upperBound => {
		acc += bucket.bucketValues[upperBound];
		const lbls = Object.assign({ le: upperBound }, bucket.labels);
		const valuePair = createValuePair(lbls, acc, `${histogram.name}_bucket`);
		return valuePair;
	};
}
~~~~
The _acc_ value is used when creating the value pairs instead of the actual bucket values and as that _acc_ value grows, so does the subsequent bucket counts in the report.
 
From this screen shot, you can see that the results in the presentation don't match the values in the Histogram object itself:
<img width="730" alt="screen shot 2018-08-16 at 5 39 41 pm" src="https://user-images.githubusercontent.com/7561730/44360712-ac1f3000-a489-11e8-80a3-f8eaacbeb0c0.png">

**Comment by siimon** [comment]
This is by design and the way Prometheus expects the data to look like. The histogram buckets are accumulated. Do you see anything wrong in the histogram in Prometheus?

**Comment by SimenB** [comment]
As mentioned, this behavior is correct. A value of 0.7 fits into the buckets 1, 5, 10, 15 and infinity. An observation is not "consumed" by the smallest bucket it fits into
