### ISSUE TITLE
Histogram scrape performance with multiple labels/label values

### ISSUE THREAD

**Issue by KevinAMurray** [siimon/prom-client#216]
Hi,

We have a use case where we are using histograms together with between 2 and 6 labels (depending on the metric), and where those labels have between 3 and 40 values.  What we are seeing is that the time to perform the scrape increases dramatically when we have more labels and more label values, to the point where the scrape operation could take a couple of seconds (for a worst case situation, which I would expect to happen after the service has been running for some time).

Whilst this clearly isn't a problem for Prometheus, in our particular case the node application is  single threaded (e.g. we cannot use Cluster or similar).  This means that a prometheus scrape will block that particular instance for a second or two whilst the scrape is happening.

I've explored the prom-client code, and I have made some improvements by effectively pre-computing information when the histogram's time series is created, and by performing some calculations during observe().  I.e. I've slightly changed the design trade-off between optimal observe() performance to improve the scrape performance, with an increase in memory requirements (though I *think* those memory requirements are probably the same when the scrape is happening).

Have other people encountered this sort of performance issue before, and are there other solutions? (As mentioned, effectively we can't use something like Cluster.)

I'm happy to provide code snippets (or a fork) as the basis of improvements or for more discussions.

Thanks,

Kevin

**Comment by SimenB** [comment]
If we have performance issues with serialising the metrics data, I think it makes sense to take a look at either our storage format or our algorithm 🙂 A test case would be awesome, so we have a baseline. Maybe look into adding benchmarks as well to the repo?

/cc @siimon @zbjornson

**Comment by KevinAMurray** [comment]
Okay -- let me look at modifying our benchmark program for histograms to provide a baseline (and allow others to check I'm not missing something obvious!)

**Comment by KevinAMurray** [comment]
Hmm. I think there is a bug in the multipliers above so the numbers will be wrong....

**Comment by SimenB** [comment]
Please give 11.1.2 a try 🙂 We can reopen if it's still an issue

**Comment by KevinAMurray** [comment]
Thanks. I'm seeing about a double in performance. Very Nice! thanks. The performance is much more linear, which is great.

The benchmark test program is sitting in [my fork in the benchmark directory](https://github.com/KevinAMurray/prom-client/tree/master/benchmarks). Shall I PR it into the main branch?

Running as `node histogram_benchmark.js -b 1,2 label_1=80 label_2=1 label_3=1 label_4=1 label_5=1` I'm still seeing a penalty for adding labels.  I'm using extra labels with a single value to show impact (thought that would normally be handled via Prometheus SD labelling). I'd expect some small performance loss from adding an extra label, but I'd hope for less.

Specifically: 
histogram_case001_2buckets_1labels_400series x 808 ops/sec ±1.40% (80 runs sampled)
histogram_case002_2buckets_2labels_400series x 555 ops/sec ±2.59% (74 runs sampled)
histogram_case003_2buckets_3labels_400series x 405 ops/sec ±3.74% (64 runs sampled)
histogram_case004_2buckets_4labels_400series x 333 ops/sec ±3.67% (67 runs sampled)
histogram_case005_2buckets_5labels_400series x 296 ops/sec ±2.22% (65 runs sampled)

Previously (I think 11.1.1), and snipped from different log (hence slight differentces):
histogram_case001_2buckets_1labels_400series x 439 ops/sec ±3.76% (61 runs sampled)
histogram_case003_2buckets_2labels_400series x 323 ops/sec ±5.75% (58 runs sampled)
histogram_case005_2buckets_3labels_400series x 93.73 ops/sec ±21.01% (27 runs sampled)
histogram_case007_2buckets_4labels_400series x 140 ops/sec ±18.33% (37 runs sampled)
histogram_case009_2buckets_5labels_400series x 138 ops/sec ±12.34% (41 runs sampled)
(I'd ignore case005 -- probably background issue on test machine).

I'll try and run some more exhaustive tests on our detailed use cases tonight.

**Comment by SimenB** [comment]
Also see #220 

I'd love to add a benchmark to this repo, feel free to PR it!

**Comment by KevinAMurray** [comment]
@SimenB, @siimon : I've been tinkering on performance using the benchmarks tools in 11.1.3 (great stuff -- many thanks for them!).

I'm pre-computing the Prometheus label string (mostly) in histogram, and I'm seeing about a 33% performance gain from this at the expense of a 10% performance drop against getMetricsAsJSON and obviously an increase in memory to hold the precomputed labels.

I'd appreciate comments on these trade-offs.  Code is currently in https://github.com/KevinAMurray/prom-client/tree/performance-metrics-scrape

(The hash used is very close to the prometheus labels, but it doesn't do the escape string. It may be possible to use the hash instead at a lesser memory overhead. I've yet to see what the performance costs of that would be. Hope to create a branch to check that idea out sometime.)

**Comment by KevinAMurray** [comment]
@nowells  I've also expanded the benchmarks a bit more now.

**Comment by nowells** [comment]
@KevinAMurray awesome! I can't wait to see how they evolve. Anything I can do to help?
