### ISSUE TITLE
Request: an option for aggregating cluster metrics that preserves worker id

### ISSUE THREAD

**Issue by vincentwoo** [siimon/prom-client#224]
For background, I run a clustered Node setup where I'm interested in things like open file descriptors *per* worker (so we can display them as a stacked graph). There's not an easy way to do this for the metrics that are collected by default. I think it'd be useful to have a general aggregation pattern where a worker just sets a particular metric, and it's pulled into the master aggregation as-is with just a worker ID label applied.

Right now we're getting around this for some metrics by having child workers use IPC to communicate back to the master, setting worker id, which is clumsy.

**Comment by zbjornson** [comment]
I agree this would be a reasonable option to offer (probably something like `collectDefaultMetrics({includeWorkerId: true})`). Happy to review a PR for it, assuming the other maintainers are good with it.
