### ISSUE TITLE
Bucket values are not respected

### ISSUE THREAD

**Issue by dohnto** [siimon/prom-client#232]
We have hundreds of applications written in several languages and using different prometheus clients. `prom-client` is one of them. When counting our SLO, we pre-calculate some recording rules where buckets from different applications are summarised to speed up calculating histogram quantiles.

So for example we use query bellow in our rule.
```
sum(request_duration_seconds_bucket) by (le)
```

In this recording rule there is an assumption, that the `le` string is always the same for all applications.
We use format of (for us reference implementation) [client_python](https://github.com/prometheus/client_python/) library.

It generates timeseries like
```
request_processing_seconds_bucket{le="1.0"} 8.0
request_processing_seconds_bucket{le="2.0"} 8.0
request_processing_seconds_bucket{le="+Inf"} 8.0
```

But `prom-client` unfortunately does not respect the floating numbers:

```
export const requestDurationSeconds = new Histogram({
	buckets: [ 0.2, 0.4, 0.8, 1.2, 2.0, 4.0, 6.0, 8.0, 12.0 ],
	help: 'Request duration in seconds.',
	labelNames: [ 'endpoint', 'method', 'status_code' ],
	name: 'request_duration_seconds',
});
```
Resulting in
```
request_duration_seconds_bucket{le="0.2",endpoint="/",...} 1
request_duration_seconds_bucket{le="0.4",endpoint="/",...} 1
request_duration_seconds_bucket{le="0.8",endpoint="/",...} 1
request_duration_seconds_bucket{le="1.2",endpoint="/",...} 1
request_duration_seconds_bucket{le="2",endpoint="/",...} 1
request_duration_seconds_bucket{le="4",endpoint="/",...} 1
request_duration_seconds_bucket{le="6",endpoint="/",...} 1
request_duration_seconds_bucket{le="8",endpoint="/",...} 1
request_duration_seconds_bucket{le="12",endpoint="/",...} 1
request_duration_seconds_bucket{le="+Inf",endpoint="/",...} 1
```

Note, that the `le` values are integers and not floats like we expect.

So when we summarise `request_duration_seconds_bucket{le="4"}` and `request_duration_seconds_bucket{le="4.0"}` it results in two timeseries.

Is there a way to say to `prom-client` in what format we want it to expose `le` label values?

Thank you for your response and reasoning for this behaviour.

**Comment by siimon** [comment]
Hm this sounds like a bug and I’m sorry to say that I don’t think there is a workaround either

**Comment by dohnto** [comment]
See https://github.com/prometheus/client_python/issues/345. Closing.
