### ISSUE TITLE
Question: About need to reset metrics

### ISSUE THREAD

**Issue by acanimal** [siimon/prom-client#236]
Hi, I was looking for similar question but do not found anything that clarify me 100% 😅 (Maybe this one #179)

I usually work using like `statsd` solution, that is, the app get some data and sends periodically to some "collector" which aggregates and stores.

Now I'm working with a different approach: I'm using `prom-client` to collect metrics and `telegraf` with prometheus input plugin to retrieve and store data at `influxdb` periodically.

The weird thing for me is the fact that my counters/histograms are always incremental, so the question is if I **need to reset them periodically** (maybe each time telegraf queries them) or can I let increase indefinitely?

Thanks !

**Comment by siimon** [comment]
You should not reset them. The reset should only be used in testing, in fact removing the reset from the public Api has crossed my mind a couple of times!

**Comment by chatoo2412** [comment]
@siimon Would you explain further?
Is it safe to count up Counter or accumulate Histogram and Summary forever?

**Comment by guyellis** [comment]
@siimon - this wasn't obvious to me either.

Okay to PR what you said at this point in the README? https://github.com/siimon/prom-client#resetting-metrics
