### ISSUE TITLE
Error when pulling from NPM

### ISSUE THREAD

**Issue by cvielma** [siimon/prom-client#24]
Hi, 

I tried to use your library which I think it's cool, but got the following error:

> bufferutil@1.1.0 install /<user_path>/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
....

According to a Google search, this seems to be related to some old libraries/dependencies (bufferutil) 

I'm using:
node v5.5.0
npm 3.5.3
MacOS 10.11.6

I couldn't see a straightforward way to fix the dependencies issues.

**Comment by siimon** [comment]
The prom-client doesn't have any dependencies to bufferutil. Are you sure this error is from the prom-client?

**Comment by cvielma** [comment]
Well, I just tried with:
node v4.4.7
npm 2.15.8
Ubuntu 12.04 and it worked. I will double check with the previous configuration and confirm where the dependency comes from.

**Comment by cvielma** [comment]
I apologize for the bad report. I'm still experiencing the same issue on MacOS, but after listing the full dependencies tree, I can't find bufferutil, so it might be an issue with the npm installation on my machine. Thanks anyways!


Here's the full dependecy tree:
npm-remote-ls prom-client
└─ prom-client@3.4.6
   ├─ chai@3.5.0
   │  ├─ deep-eql@0.1.3
   │  │  └─ type-detect@0.1.1
   │  ├─ assertion-error@1.0.2
   │  └─ type-detect@1.0.0
   ├─ util-extend@1.0.3
   ├─ tdigest@0.1.1
   │  └─ bintrees@1.0.1
   ├─ nock@8.0.0
   │  ├─ debug@2.2.0
   │  │  └─ ms@0.7.1
   │  ├─ json-stringify-safe@5.0.1
   │  ├─ chai@3.5.0
   │  ├─ propagate@0.4.0
   │  ├─ mkdirp@0.5.1
   │  │  └─ minimist@0.0.8
   │  ├─ lodash@4.15.0
   │  ├─ qs@6.2.1
   │  └─ deep-equal@1.0.1
   ├─ express@4.14.0
   │  ├─ accepts@1.3.3
   │  │  ├─ mime-types@2.1.11
   │  │  │  └─ mime-db@1.23.0
   │  │  └─ negotiator@0.6.1
   │  ├─ debug@2.2.0
   │  ├─ content-type@1.0.2
   │  ├─ cookie-signature@1.0.6
   │  ├─ array-flatten@1.1.1
   │  ├─ depd@1.1.0
   │  ├─ encodeurl@1.0.1
   │  ├─ escape-html@1.0.3
   │  ├─ fresh@0.3.0
   │  ├─ finalhandler@0.5.0
   │  │  ├─ debug@2.2.0
   │  │  ├─ unpipe@1.0.0
   │  │  ├─ escape-html@1.0.3
   │  │  ├─ statuses@1.3.0
   │  │  └─ on-finished@2.3.0
   │  ├─ etag@1.7.0
   │  ├─ content-disposition@0.5.1
   │  ├─ on-finished@2.3.0
   │  │  └─ ee-first@1.1.1
   │  ├─ parseurl@1.3.1
   │  ├─ methods@1.1.2
   │  ├─ qs@6.2.0
   │  ├─ range-parser@1.2.0
   │  ├─ proxy-addr@1.1.2
   │  │  ├─ forwarded@0.1.0
   │  │  └─ ipaddr.js@1.1.1
   │  ├─ merge-descriptors@1.0.1
   │  ├─ utils-merge@1.0.0
   │  ├─ cookie@0.3.1
   │  ├─ send@0.14.1
   │  │  ├─ debug@2.2.0
   │  │  ├─ depd@1.1.0
   │  │  ├─ encodeurl@1.0.1
   │  │  ├─ escape-html@1.0.3
   │  │  ├─ etag@1.7.0
   │  │  ├─ fresh@0.3.0
   │  │  ├─ destroy@1.0.4
   │  │  ├─ ms@0.7.1
   │  │  ├─ mime@1.3.4
   │  │  ├─ range-parser@1.2.0
   │  │  ├─ on-finished@2.3.0
   │  │  ├─ statuses@1.3.0
   │  │  └─ http-errors@1.5.0
   │  │     ├─ inherits@2.0.1
   │  │     ├─ setprototypeof@1.0.1
   │  │     └─ statuses@1.3.0
   │  ├─ type-is@1.6.13
   │  │  ├─ media-typer@0.3.0
   │  │  └─ mime-types@2.1.11
   │  ├─ serve-static@1.11.1
   │  │  ├─ escape-html@1.0.3
   │  │  ├─ encodeurl@1.0.1
   │  │  ├─ parseurl@1.3.1
   │  │  └─ send@0.14.1
   │  ├─ vary@1.1.0
   │  └─ path-to-regexp@0.1.7
   ├─ mocha@2.5.3
   │  ├─ debug@2.2.0
   │  ├─ commander@2.3.0
   │  ├─ escape-string-regexp@1.0.2
   │  ├─ growl@1.9.2
   │  ├─ glob@3.2.11
   │  │  ├─ inherits@2.0.1
   │  │  └─ minimatch@0.3.0
   │  │     ├─ sigmund@1.0.1
   │  │     └─ lru-cache@2.7.3
   │  ├─ supports-color@1.2.0
   │  ├─ mkdirp@0.5.1
   │  ├─ jade@0.26.3
   │  │  ├─ commander@0.6.1
   │  │  └─ mkdirp@0.3.0
   │  ├─ to-iso-string@0.0.2
   │  └─ diff@1.4.0
   ├─ eslint@2.13.1
   │  ├─ chalk@1.1.3
   │  │  ├─ ansi-styles@2.2.1
   │  │  ├─ escape-string-regexp@1.0.5
   │  │  ├─ has-ansi@2.0.0
   │  │  │  └─ ansi-regex@2.0.0
   │  │  ├─ strip-ansi@3.0.1
   │  │  │  └─ ansi-regex@2.0.0
   │  │  └─ supports-color@2.0.0
   │  ├─ debug@2.2.0
   │  ├─ concat-stream@1.5.1
   │  │  ├─ inherits@2.0.1
   │  │  ├─ typedarray@0.0.6
   │  │  └─ readable-stream@2.0.6
   │  │     ├─ core-util-is@1.0.2
   │  │     ├─ inherits@2.0.1
   │  │     ├─ isarray@1.0.0
   │  │     ├─ process-nextick-args@1.0.7
   │  │     ├─ string_decoder@0.10.31
   │  │     └─ util-deprecate@1.0.2
   │  ├─ doctrine@1.2.3
   │  │  ├─ isarray@1.0.0
   │  │  └─ esutils@2.0.2
   │  ├─ es6-map@0.1.4
   │  │  ├─ es6-set@0.1.4
   │  │  │  ├─ d@0.1.1
   │  │  │  ├─ es6-iterator@2.0.0
   │  │  │  ├─ es5-ext@0.10.12
   │  │  │  ├─ es6-symbol@3.1.0
   │  │  │  └─ event-emitter@0.3.4
   │  │  ├─ d@0.1.1
   │  │  │  └─ es5-ext@0.10.12
   │  │  ├─ es6-iterator@2.0.0
   │  │  │  ├─ d@0.1.1
   │  │  │  ├─ es6-symbol@3.1.0
   │  │  │  └─ es5-ext@0.10.12
   │  │  ├─ es6-symbol@3.1.0
   │  │  │  ├─ d@0.1.1
   │  │  │  └─ es5-ext@0.10.12
   │  │  ├─ es5-ext@0.10.12
   │  │  │  ├─ es6-iterator@2.0.0
   │  │  │  └─ es6-symbol@3.1.0
   │  │  └─ event-emitter@0.3.4
   │  │     ├─ d@0.1.1
   │  │     └─ es5-ext@0.10.12
   │  ├─ esutils@2.0.2
   │  ├─ file-entry-cache@1.3.1
   │  │  ├─ object-assign@4.1.0
   │  │  └─ flat-cache@1.2.1
   │  │     ├─ circular-json@0.3.1
   │  │     ├─ write@0.2.1
   │  │     │  └─ mkdirp@0.5.1
   │  │     ├─ graceful-fs@4.1.5
   │  │     └─ del@2.2.2
   │  │        ├─ is-path-cwd@1.0.0
   │  │        ├─ globby@5.0.0
   │  │        │  ├─ arrify@1.0.1
   │  │        │  ├─ object-assign@4.1.0
   │  │        │  ├─ glob@7.0.5
   │  │        │  ├─ pify@2.3.0
   │  │        │  ├─ pinkie-promise@2.0.1
   │  │        │  └─ array-union@1.0.2
   │  │        │     └─ array-uniq@1.0.3
   │  │        ├─ is-path-in-cwd@1.0.0
   │  │        │  └─ is-path-inside@1.0.0
   │  │        │     └─ path-is-inside@1.0.1
   │  │        ├─ pify@2.3.0
   │  │        ├─ object-assign@4.1.0
   │  │        ├─ pinkie-promise@2.0.1
   │  │        │  └─ pinkie@2.0.4
   │  │        └─ rimraf@2.5.4
   │  │           └─ glob@7.0.5
   │  ├─ escope@3.6.0
   │  │  ├─ es6-map@0.1.4
   │  │  ├─ es6-weak-map@2.0.1
   │  │  │  ├─ d@0.1.1
   │  │  │  ├─ es6-iterator@2.0.0
   │  │  │  ├─ es5-ext@0.10.12
   │  │  │  └─ es6-symbol@3.1.0
   │  │  ├─ esrecurse@4.1.0
   │  │  │  ├─ estraverse@4.1.1
   │  │  │  └─ object-assign@4.1.0
   │  │  └─ estraverse@4.2.0
   │  ├─ estraverse@4.2.0
   │  ├─ glob@7.0.5
   │  │  ├─ fs.realpath@1.0.0
   │  │  ├─ inflight@1.0.5
   │  │  │  ├─ once@1.3.3
   │  │  │  └─ wrappy@1.0.2
   │  │  ├─ inherits@2.0.1
   │  │  ├─ once@1.3.3
   │  │  │  └─ wrappy@1.0.2
   │  │  ├─ path-is-absolute@1.0.0
   │  │  └─ minimatch@3.0.3
   │  │     └─ brace-expansion@1.1.6
   │  │        ├─ balanced-match@0.4.2
   │  │        └─ concat-map@0.0.1
   │  ├─ espree@3.1.7
   │  │  ├─ acorn-jsx@3.0.1
   │  │  │  └─ acorn@3.3.0
   │  │  └─ acorn@3.3.0
   │  ├─ globals@9.9.0
   │  ├─ json-stable-stringify@1.0.1
   │  │  └─ jsonify@0.0.0
   │  ├─ is-my-json-valid@2.13.1
   │  │  ├─ generate-function@2.0.0
   │  │  ├─ generate-object-property@1.2.0
   │  │  │  └─ is-property@1.0.2
   │  │  ├─ jsonpointer@2.0.0
   │  │  └─ xtend@4.0.1
   │  ├─ is-resolvable@1.0.0
   │  │  └─ tryit@1.0.2
   │  ├─ js-yaml@3.6.1
   │  │  ├─ argparse@1.0.7
   │  │  │  └─ sprintf-js@1.0.3
   │  │  └─ esprima@2.7.2
   │  ├─ ignore@3.1.5
   │  ├─ imurmurhash@0.1.4
   │  ├─ inquirer@0.12.0
   │  │  ├─ ansi-escapes@1.4.0
   │  │  ├─ cli-cursor@1.0.2
   │  │  │  └─ restore-cursor@1.0.1
   │  │  │     ├─ exit-hook@1.1.1
   │  │  │     └─ onetime@1.1.0
   │  │  ├─ ansi-regex@2.0.0
   │  │  ├─ chalk@1.1.3
   │  │  ├─ figures@1.7.0
   │  │  │  ├─ escape-string-regexp@1.0.5
   │  │  │  └─ object-assign@4.1.0
   │  │  ├─ run-async@0.1.0
   │  │  │  └─ once@1.3.3
   │  │  ├─ lodash@4.15.0
   │  │  ├─ cli-width@2.1.0
   │  │  ├─ strip-ansi@3.0.1
   │  │  ├─ rx-lite@3.1.2
   │  │  ├─ through@2.3.8
   │  │  ├─ string-width@1.0.2
   │  │  │  ├─ code-point-at@1.0.0
   │  │  │  │  └─ number-is-nan@1.0.0
   │  │  │  ├─ is-fullwidth-code-point@1.0.0
   │  │  │  │  └─ number-is-nan@1.0.0
   │  │  │  └─ strip-ansi@3.0.1
   │  │  └─ readline2@1.0.1
   │  │     ├─ code-point-at@1.0.0
   │  │     ├─ is-fullwidth-code-point@1.0.0
   │  │     └─ mute-stream@0.0.5
   │  ├─ path-is-absolute@1.0.0
   │  ├─ mkdirp@0.5.1
   │  ├─ path-is-inside@1.0.1
   │  ├─ lodash@4.15.0
   │  ├─ progress@1.1.8
   │  ├─ strip-json-comments@1.0.4
   │  ├─ pluralize@1.2.1
   │  ├─ optionator@0.8.1
   │  │  ├─ wordwrap@1.0.0
   │  │  ├─ levn@0.3.0
   │  │  ├─ type-check@0.3.2
   │  │  │  └─ prelude-ls@1.1.2
   │  │  ├─ deep-is@0.1.3
   │  │  ├─ prelude-ls@1.1.2
   │  │  └─ fast-levenshtein@1.1.4
   │  ├─ require-uncached@1.0.2
   │  │  ├─ caller-path@0.1.0
   │  │  │  └─ callsites@0.2.0
   │  │  └─ resolve-from@1.0.1
   │  ├─ text-table@0.2.0
   │  ├─ shelljs@0.6.1
   │  ├─ user-home@2.0.0
   │  │  └─ os-homedir@1.0.1
   │  ├─ table@3.7.8
   │  │  ├─ chalk@1.1.3
   │  │  ├─ string-width@1.0.2
   │  │  ├─ lodash@4.15.0
   │  │  ├─ strip-ansi@3.0.1
   │  │  ├─ bluebird@3.4.1
   │  │  ├─ xregexp@3.1.1
   │  │  ├─ tv4@1.2.7
   │  │  └─ slice-ansi@0.0.4
   │  └─ levn@0.3.0
   │     ├─ prelude-ls@1.1.2
   │     └─ type-check@0.3.2
   └─ sinon@1.17.5
      ├─ util@0.10.3
      │  └─ inherits@2.0.1
      ├─ lolex@1.3.2
      ├─ samsam@1.1.2
      └─ formatio@1.1.1
         └─ samsam@1.1.3

**Comment by cvielma** [comment]
BTW dowgrading to 4.47 on MacOS fixed the issue.
