### ISSUE TITLE
Unable to get Counter value

### ISSUE THREAD

**Issue by brian-byungsookim** [siimon/prom-client#245]
Hi,

I'm using this library in my Typescript code and am having trouble accessing the value of a Counter.

### Questions:
1. I see that you're able to access a Counter's value in the [counterTest.js](https://github.com/siimon/prom-client/blob/master/test/counterTest.js#L20), but you're not able to use the `get` method when using the library as a dependency as it is neither a part of the Counter nor other metrics' API. If you don't mind, do you mind explaining the reasoning behind not including that method?
2. Since the above idea didn't work, I tried to access the metric via `getSingleMetric`, but that method returns an [object with type `Metric`](https://github.com/siimon/prom-client/blob/master/index.d.ts#L59) (and not `metric` or `metric[]` like others). And since `Metric` is  a [union type of metrics](https://github.com/siimon/prom-client/blob/master/index.d.ts#L127), I end up in the exact same place above, with a Counter object that doesn't have a `get` method.

Any pointers or thoughts? Thanks

**Comment by siimon** [comment]
The get function is a private function not meant to be a part of the public api. prom- client should not expose the metrics themselves, rather the value of all them. 

What are you trying to do?

**Comment by aaronleesmith** [comment]
I can say I'm working on unit tests which would benefit from the ability to get the count on a given metric. That's a good use-case example.

**Comment by sam-github** [comment]
For a unit test, I would suggest putting the counter in a registry (make one specifically for the test), call `reg.metrics()`, parse value from there.

Close this as won't fix?
