### ISSUE TITLE
keep counter after worker restart

### ISSUE THREAD

**Issue by lynhnn** [siimon/prom-client#250]
In a cluster env, I regularly restart workers and cluster metrics counters are going down after losing that worker counter. Is there a way to address or to workaround this?

**Comment by zbjornson** [comment]
I think using pushgateway *without* the cluster module would be the best option. Each worker would push their metrics (with a unique job and/or instance label) to the pushgateway before going down. If you need real-time monitoring in addition to that after-the-fact monitoring, I think it'd work to use the cluster module for real-time, and pushgateway for after-the-fact.

https://github.com/siimon/prom-client#pushgateway
https://github.com/prometheus/pushgateway
Also consider https://github.com/prometheus/node_exporter/blob/master/README.md#textfile-collector
