### ISSUE TITLE
prefix causes 'Invalid metric name'

### ISSUE THREAD

**Issue by vance** [siimon/prom-client#252]
just doing a standard 
```
const prefix = 'some_service_name';
collectDefaultMetrics({ timeout: 10000, prefix, register: promRegistry });
```

but i get `Error: Invalid metric name` 

Maybe I am misunderstanding how prefix works? I need to track multiple services running in a docker swarm, and I want custom prefixes so I know which app metrics are coming from when they hit the push gateway. 

any help appreciated!

**Comment by den-vasyliev** [comment]
got same
collectDefaultMetrics({ prefix: 'name_' });

**Comment by zbjornson** [comment]
@vance @den-vasyliev can you post full minimal examples please? The following works for me with the latest version:

```js
const promClient = require("prom-client");
promClient.collectDefaultMetrics({prefix: "name_"});
```

Since v11.5.0 there's a function `promClient.validateMetricName` that you can also use. @vance maybe `some_service_name` contains invalid character sequences.

**Comment by zbjornson** [comment]
Per above I can't reproduce this. Will reopen if anyone can provide more info.

**Comment by mahapajapati** [comment]
The same problem here, using version 14.0.1 and following this example: https://codesandbox.io/s/next-js-api-prom-client-hhvdi?file=/pages/api/metrics.ts 

I'm only adding 
`collectDefaultMetrics({ prefix: 'my-prefix' })` and I get:

Error: Invalid metric name

![ksnip_20211222-125216](https://user-images.githubusercontent.com/28458720/147127645-c524e512-42a7-4b01-b059-6393f601e179.png)
