### ISSUE TITLE
Metrics change by router can't show value but Interval can

### ISSUE THREAD

**Issue by Kuro-P** [siimon/prom-client#257]
I add those code to example/cluster.js
````javascript

const counter = new Counter({
   name: 'master_counter',
   help: 'Example of a master counter',
   labelNames: ['master_counter']
});

setInterval(() => {
    counter.inc({
        master_counter: 'by_interval'
    })
}, 500)

if (cluster.isMaster) {
    cluster.fork();
    metricsServer.get('/', (req, res) => {
        counter.inc({ master_counter: 'by_router' });
        res.json({ status: 'ok' });
    })

    metricsServer.get('/metrics', (req, res) => {
        res.set('Content-Type', Prometheus.register.contentType)
        res.end(Prometheus.register.metrics())
    })

   metricsServer.listen(3001);
} else {
   require('./server.js');
}
````
then I visited port 3001 /metrics to check the master_counter value:
````
# HELP master_counter Example of a master counter
# TYPE master_counter counter
master_counter{master_counter="by_interval"} 1930
master_counter{master_counter="by_router"} 3
````
but server port 3000 /metrics result doesn't show master_couter "by_router" value :
````
# HELP master_counter Example of a master counter
# TYPE master_counter counter
master_counter{master_counter="by_interval"} 1891
````
I'm confused about that result.

**Comment by zbjornson** [comment]
The server on port 3000 is the cluster worker. You're only incrementing the counter with `"by_router"` in the cluster master (port 3001). Is that what you're wondering about?

**Comment by Kuro-P** [comment]
Yes, i wonder to know why counter `by_router` doesn't show on port 3000.

**Comment by zbjornson** [comment]
That's because `counter.inc({ master_counter: 'by_router' });` is inside the `if (cluster.isMaster)` block. The cluster worker (port 3000) doesn't have a counter value with that label.

---

In a cluster environment, you're only intended to query the master (3001) for metrics, which it aggregates from the workers. It's not generally useful to query the workers (3000).

**Comment by Kuro-P** [comment]
Got it, thanks a lot!
