### ISSUE TITLE
Split process request and process handles by type

### ISSUE THREAD

**Issue by yvasiyarov** [siimon/prom-client#268]
Hello @SimenB, 
can you please have a look at  pr #260 ?
It did hear anything from you for a week.

It would be very nice if you can help me get this pr merged in the upstream.

**Comment by randotarvina** [comment]
Looks useful !!  +1

**Comment by JekaMas** [comment]
Sounds really useful for our projects too (Ethereum geth client and proof of autority fork Autonity used by European Blockchain Alliance).
Is there any reason why it hasn't been merged yet?

**Comment by screwyprof** [comment]
Would be really nice to have it merged!

**Comment by Ada-Agava** [comment]
Useful metrics, please be so kind to merge

**Comment by major28** [comment]
+1

**Comment by VyacheslavErmakov** [comment]
+100500

**Comment by polosate** [comment]
+1

**Comment by emikhalev** [comment]
+1

**Comment by emikhalev** [comment]
+1

**Comment by SimenB** [comment]
No need for a nagging thread, we all work on this for free in our spare time :heart:
