### ISSUE TITLE
prom-client metrics route hangs pm2 indefinetly 

### ISSUE THREAD

**Issue by shubh-07** [siimon/prom-client#272]
I am using pm2 to run multiple express and micro-service API's.
In one of the express API's i am using prom-client(Prometheus client for node.js) to return prometheus metrics for that API.
I have created a /metrics route in the express API which aggregate metrics from all the instances and returns metrics for the API.
Prometheus is a pull system so it scrapes data from that API every minute(default duration).
Now the system works perfectly fine for 4-5 days when scrape duration is 1 min but after that PM2 hangs for indefinite time resulting in blocking of all the API's running through PM2 on the system.

I also tested this scenario by reducing scrape duration to 5 sec. And after that i noticed pm2 got hung in 4-5 hours.

pm2 -v - 3.5.0
node -v - 8.11.4
prom-client -v - latest

**Comment by zbjornson** [comment]
My go-to method for figuring out what Node.js is doing when it's hung is to attach the debugger and pause its execution. https://nodejs.org/de/docs/guides/debugging-getting-started/ has info on how to attach the debugger -- either start node with `--inspect` or send `SIGUSR1` to an already-running process. Once you've done that, you will hopefully be able to see if it's caught in some infinite loop.

**Comment by zbjornson** [comment]
If you're still encountering this problem, let us know and I'll re-open the issue. I'm guessing it's in pm2 and not prom-client however.
