### ISSUE TITLE
Is there a way to get clusterMetrics from workers?

### ISSUE THREAD

**Issue by euvs** [siimon/prom-client#292]
My app is running in a cluster mode. The example for the cluster mode uses two different ports, where one port is used by the master process to serve aggregated metrics, and the other for all other APIs. My problem is that I'm running my app on Heroku, and Heroku does not allow opening two ports AFAIK.

Calling `aggregatorRegistry.clusterMetrics` does not seem to work if called from a worker. Is it somehow possible to access the metrics aggregated by the master process from workers? Or is it a bad idea?

**Comment by zbjornson** [comment]
You can use the same port, but for security it's easier to use two ports (your public server port, plus your private metrics port). If you use a single public port, you could use some form of authentication for the metrics scrape endpoint to lock it down.

`clusterMetrics()` can't work from a worker. You could rig something up with cluster-worker communication, but I don't think that would solve your problem and would be pretty clunky.

**Comment by zbjornson** [comment]
Hm, rereading ... you might need to use cluster-worker communication actually. There's an example in the Node.js docs here https://nodejs.org/dist/latest-v12.x/docs/api/cluster.html#cluster_event_message, and it would look similar to the messaging that happens in this module here https://github.com/siimon/prom-client/blob/f32685708957fac2d4f0ce455c6af4d2e79dc5ed/lib/cluster.js#L158.

The only other easy-ish alternative I can think of is to use Node.js to proxy metrics requests to the separate server.

(Need to run -- let me know if you need more guidance and I can answer later today or tomorrow.)

**Comment by euvs** [comment]
Thanks for your reply. It looks like I'll have to implement a cluster-worker communication myself as you suggested. I was hoping there were be a built-in feature that I missed somehow. No worries, I'll give it a go. Shouldn't be that hard, right? ;)

**Comment by zbjornson** [comment]
Closing to clean up issues. Leave a note if you need assistance!
