### ISSUE TITLE
Why can't metrics be distributed (or at least persist with distributed memcached/redis)?

### ISSUE THREAD

**Issue by HuskyMoonMoon** [siimon/prom-client#295]
We have some metrics that depends on tenancy such as `bytes_processed_total` counter that labeled with user's `tenant_id`, data processing is online with scalable microservice. Metrics exporter `/metrics` should be accessed through load balancer. 

But when it comes to scale, the counter metrics of newly spawned service instance is 0, counter metrics stored in Prometheus is reset when the scraping request hit the instance.

I'm not considered using PushGateway because it's online processing.

As @siimon stated in #207 

> Because it introduces a layer it wasn't designed for. Prometheus is designed for scraping the targets directly or through a push gateway (which is officially maintained).

Why the application which is behind load balancer or distributed is not considered as "direct target" to scrape since all application instances has been combined to a single entry point, all instances of distributed application actually considered as one application domain. Or Prometheus only considered from infrastructure operation perspective?

Strange...right?

**Comment by zbjornson** [comment]
I'm not entirely sure what you're asking.

> Metrics exporter /metrics should be accessed through load balancer.

Prometheus should *not* scrape through a load balancer, otherwise you will only scrape one particular target instead of all of your targets. The prometheus server + your prometheus queries take care of aggregating all of the targets.
