### ISSUE TITLE
Support Grafana histogram by renaming quantile label to le

### ISSUE THREAD

**Issue by jorkzijlstra** [siimon/prom-client#300]
Using a Summary you get a nice dataset in the form of a histogram. 
I think the most common dashboard to use with Prometheus is Grafana which has this in its docs:

https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile
```
Each sample must have a label le where the label value denotes the inclusive upper bound of the bucket
```

Currently you can't use the histogram data in combination with Grafana

**Comment by zbjornson** [comment]
When you create a histogram, each bucket that you specify defines an `le` label. For example:

```js
new prometheus.Histogram({
	name: "rpc_gcs_rlat",
	help: "Read latency",
	buckets: prometheus.linearBuckets(0.020, 0.010, 19) // 20..200ms in steps of 10
});
```

is exposed as 

```
# HELP rpc_gcs_rlat Read latency
# TYPE rpc_gcs_rlat histogram
rpc_gcs_rlat_bucket{le="0.02"} 0
rpc_gcs_rlat_bucket{le="0.03"} 0
rpc_gcs_rlat_bucket{le="0.04"} 0
rpc_gcs_rlat_bucket{le="0.05"} 0
rpc_gcs_rlat_bucket{le="0.060000000000000005"} 0
rpc_gcs_rlat_bucket{le="0.07"} 0
rpc_gcs_rlat_bucket{le="0.08"} 0
rpc_gcs_rlat_bucket{le="0.09"} 0
rpc_gcs_rlat_bucket{le="0.09999999999999999"} 0
rpc_gcs_rlat_bucket{le="0.10999999999999999"} 0
rpc_gcs_rlat_bucket{le="0.11999999999999998"} 0
rpc_gcs_rlat_bucket{le="0.12999999999999998"} 0
rpc_gcs_rlat_bucket{le="0.13999999999999999"} 0
rpc_gcs_rlat_bucket{le="0.15"} 0
rpc_gcs_rlat_bucket{le="0.16"} 0
rpc_gcs_rlat_bucket{le="0.17"} 0
rpc_gcs_rlat_bucket{le="0.18000000000000002"} 0
rpc_gcs_rlat_bucket{le="0.19000000000000003"} 0
rpc_gcs_rlat_bucket{le="0.20000000000000004"} 0
rpc_gcs_rlat_bucket{le="+Inf"} 0
rpc_gcs_rlat_sum 0
rpc_gcs_rlat_count 0
```

and then you can display that in Grafana with `histogram_quantile` like

```
histogram_quantile(0.9, sum(rate(rpc_gcs_rlat_bucket[5m])) by (le))
```

If that doesn't address what you're trying to do, can you clarify your question please?

**Comment by jorkzijlstra** [comment]
That is indeed what I'm expecting, but for some reason we are getting:
```
http_request_duration_ms{quantile="0.05",method="GET",path="/",status="200"} 0
```

So the `le` is `quantile` here. If you say it should already be `le` then Ill need to debug some further

**Comment by zbjornson** [comment]
Ah sorry, I'm talking about Histograms but you're using a Summary ([described](https://prometheus.io/docs/concepts/metric_types/#histogram), [compared](https://prometheus.io/docs/practices/histograms/)). You shouldn't use `histogram_quantile` with Summaries because the quantiles are calculated by the client (prom-client).

**Comment by jorkzijlstra** [comment]
Thnx, we will need to change to the Histogram then and figure out how to specify the buckets in advance.
