### ISSUE TITLE
Recommended way to handle multiple servers?

### ISSUE THREAD

**Issue by rubencodes** [siimon/prom-client#301]
I'm looking to use `prom-client` on a project hosted across multiple servers. I see the recommended approach for handling a cluster on one server, but is there any guidance on how to handle multiple servers? Right now the best I could think is to manually ping each one individually, but I'd love to hear if there's a better approach.

Thank you!

**Comment by zbjornson** [comment]
This is usually (always?) handled by the prometheus server, which scrapes all of your targets ("jobs" and "instances") and gathers them into a single database so they can be queried together. Is that what you're asking?

**Comment by rubencodes** [comment]
I believe so. So if there's a number of servers involved, the prometheus server should be responsible for pinging each one, and aggregating their metrics into one database, yes?

**Comment by zbjornson** [comment]
Correct, that's what prometheus server is designed to do.

**Comment by rubencodes** [comment]
Thank you!
