### ISSUE TITLE
Default stats for memory and CPU usage

### ISSUE THREAD

**Issue by jsha** [siimon/prom-client#31]
Node provides built-in ways to get CPU and memory usage information from the `process` package:

https://nodejs.org/api/process.html#process_process_cpuusage_previousvalue
https://nodejs.org/api/process.html#process_process_memoryusage

It would be useful to provide these as exported variables by default. This would be in keeping with practice of other Prometheus clients, like the [Go client](https://github.com/prometheus/client_golang). Would you be open to a patch?

**Comment by siimon** [comment]
There is already a PR open for this, see https://github.com/siimon/prom-client/pull/25!

I think it's pretty close a merge so should hopefully be published next week.
