### ISSUE TITLE
process_max_fds is reporting system limit, not the process limit

### ISSUE THREAD

**Issue by sam-github** [siimon/prom-client#311]
I think  this is a bug.

`process_max_fds` is using [`/proc/sys/fs/file-max`](https://github.com/siimon/prom-client/blob/cc9ce780ce59207c48fec79c539de947801348ee/lib/metrics/processMaxFileDescriptors.js#L28) which is

> a system-wide limit on the number of open files for all processes

This is the _OS_ limit, not the _process_ limit.

The process limit can be read from `/proc/self/limits`.

See http://man7.org/linux/man-pages/man5/proc.5.html for the /proc docs, which can't be deep linked into, sorry.

I might be able to find time to fix this if its agreed its wrong, but not today.

**Comment by SimenB** [comment]
I think I wrote that one a couple of years ago, and I didn't purposefully take the OS limit. PR very much welcome 🙂

I _think_ I based it on https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java#L82 which comes from `osBean`, which I probably just googled and went with first I found 😅

**Comment by sam-github** [comment]
I check, go's promclient uses `/proc/[pid]/limits`: 
https://github.com/prometheus/procfs/blob/496ec92a4c3ca16a9902b10e44fc80628ed72745/proc_limits.go#L121

I'm working on this.
