### ISSUE TITLE
How to export metric into remote storage

### ISSUE THREAD

**Issue by mituso89** [siimon/prom-client#326]
I am using prom-client to export metric however i can't figure out how to export metric into remote storage. I just can export metric to local storage. Pls help me any suggestion.
I see a example of .net have register metric sever 
![image](https://user-images.githubusercontent.com/29556841/73506529-6994ad80-4408-11ea-9b35-a6787f132d88.png)
This is link: https://github.com/prometheus-net/prometheus-net
Any the same method for prom-client in nodejs
Thank you so much

**Comment by siimon** [comment]
What do you mean by remote storage? All the metrics is stored in memory and there is no support for saving the metrics in a remote storage. 

What are you trying to do?

**Comment by sam-github** [comment]
@mituso89 The .net example code you posted is essentiall the same as https://github.com/siimon/prom-client/blob/master/example/server.js, remove everything *except* the folloowing sections, and its pretty much the same thing:

- https://github.com/siimon/prom-client/blob/9b4ef105cbc914e0ca50d9fbca9113deeb3db663/example/server.js#L1-L6
- https://github.com/siimon/prom-client/blob/9b4ef105cbc914e0ca50d9fbca9113deeb3db663/example/server.js#L15-L20
- https://github.com/siimon/prom-client/blob/9b4ef105cbc914e0ca50d9fbca9113deeb3db663/example/server.js#L42-L44
- https://github.com/siimon/prom-client/blob/9b4ef105cbc914e0ca50d9fbca9113deeb3db663/example/server.js#L72-L75
- https://github.com/siimon/prom-client/blob/9b4ef105cbc914e0ca50d9fbca9113deeb3db663/example/server.js#L88-L89
