### ISSUE TITLE
Registering a metric twice

### ISSUE THREAD

**Issue by trystanj** [siimon/prom-client#33]
Hi! I found myself using this library in perhaps a strange way. Essentially, prom-client was registering a metric twice, which messes up the scraper. In general the solution is to not have multiple metrics with the same name, but I couldn't find a clean way around it.

In a shared lib, I registered a metric. Another dependency used that same shared lib as a dependency. Both are listed in their respective `package.json` as a git repo url for various reasons. This has the side effect that npm does not dedupe the dependency. Essentially, then, the metric name was registered twice, which caused the prometheus scraper to report `text format parsing error in line #: second HELP line for metric name "<metric_name>"`.

I'm working on a PR that prevents a metric from being registered twice. I am no prometheus expert, so I would appreciate input on if this might be a bad idea! My first thought is that users of prom-client might not expect this behavior and could accidentally mix metrics (though, I think using labels properly would avoid this, yes?) My second thought is that my use case is pathological and I should not change the lib to work around it (in which case, any suggestions? use and escape `__dirname` appended to the metric name and have prometheus aggregate across all metrics with my metric_name prefix?)

All the tests pass, but something tells me this might be a bigger change than I think and just should be a larger version hop, but I leave that up to you!

**Comment by siimon** [comment]
Hi!

I investigated this some time ago and did the same thing in the official Python client, and it accepts metrics with the same name - so I then decided to follow that convention.

**Comment by trystanj** [comment]
So do you think this is worth trying to solve for in prom-client? Or find another way to work around it? I'm happy to keep working on a solution but if you don't think it belongs in the client then I won't worry about it!

**Comment by siimon** [comment]
No, I don't think this should be solved in prom-client :)
