### ISSUE TITLE
Use perf_hooks monitorEventLoopDelay() instead of own monitoring

### ISSUE THREAD

**Issue by voxpelli** [siimon/prom-client#331]
Since Node v11.10.0 Node.js has built in support for monitoring event loop delay: https://nodejs.org/api/perf_hooks.html#perf_hooks_perf_hooks_monitoreventloopdelay_options

I would suggest to use that rather than then current tracking:

https://github.com/siimon/prom-client/blob/9b4ef105cbc914e0ca50d9fbca9113deeb3db663/lib/metrics/eventLoopLag.js#L26-L27

**Comment by SimenB** [comment]
This is being worked on in #278

**Comment by voxpelli** [comment]
Oh, my search skills failed me 🙈 Let’s close this one then
