### ISSUE TITLE
client.collectDefaultMetrics() does not return an interval

### ISSUE THREAD

**Issue by y0y0z** [siimon/prom-client#342]
from the documentation

> collectDefaultMetrics returns an identification when invoked, which is a reference to the Timer used to keep the probes going. This can be passed to clearInterval in order to stop all probes.

but when trying the following
```javascript
const client = require("prom-client");
const interval = client.collectDefaultMetrics();
```
`interval` is equal to `undefined`.

**Comment by SimenB** [comment]
Yeah, removed in v12. Will be updated in #337
