### ISSUE TITLE
Same metric name but different label

### ISSUE THREAD

**Issue by svettwer** [siimon/prom-client#347]
Hi everybody! :wave:

I'm currently working on a prometheus integration for [Sakuli](https://github.com/sakuli) E2E application monitoring. I'm facing an issue and as I'm new to prometheus I don't know if I have misunderstood the concepts of prometheus gauges or if it might be an issue with the registry of the library.

Based on the [prometheus datal mode specification](https://prometheus.io/docs/concepts/data_model/), registering a gauge with the same name but different labels should be possible.
E.g.:
```
api_http_requests_total{method="POST", handler="/messages"}
api_http_requests_total{method="GET", handler="/messages"}
```
One gauge would store the amount of `GET` requests and one would store the amount of `POST` requests for the `/message` endpoint. But when I try to realize this with the prom client, I receive a `Error: A metric with the name <myMetricName> has already been registered.`

My question is, have I misunderstood the specification and the upper scenario would not work at all or is it the library that blocks a gauge creation that should be possible?

I'm creating my gauges like
```typescript
function createGauge(gaugeDefinition: GaugeDefinition){
    let gaugeConfiguration: GaugeConfiguration = {
        name: verifyGaugeName(gaugeDefinition.name),
        help: gaugeDefinition.help,
        labelNames: Object.keys(gaugeDefinition.labels)
    };

    const gauge = new Gauge(gaugeConfiguration);
    gauge.set(gaugeDefinition.labels, gaugeDefinition.measurement);
}
```

Any help would be highly appreciated.
Thanks in advance and best regards
Sven

**Comment by sam-github** [comment]
I think data model and API aren't the same thing.

> One gauge would store the amount of GET requests and one would store the amount of POST requests

That sounds like you think there are two gauges... but there is only one gauge, and it has two dimensions ("method" and "handler"). It looks to me like you should create one gauge, and pass it to the places that need it (the GET and POST handlers, I assume).

**Comment by svettwer** [comment]
Thx a lot for your response! :+1: 
So instead of creating two gauges, I'd create one and call `set` two times with different dimensions?

BR
Sven

**Comment by svettwer** [comment]
As assumed, reusing the gauge solved the issue:

```typescript
    let gauge = register.getSingleMetric(gaugeDefinition.name) as Gauge;
    if(!gauge){
        gauge = registerNewGauge(gaugeDefinition);
    }
```

Thx a lot! :tada:
