### ISSUE TITLE
ignore push duplicated values as we need to optimize data, but diagram is broken

### ISSUE THREAD

**Issue by HadiAbbasi** [siimon/prom-client#349]
Hey Guys...
I wanna try to send only  modified data and prevent to send duplicated data!
my simplified code is this:

```
const client = require('prom-client');
const gateway = new client.Pushgateway(config.prometheus_ip_port);

var mainFunc = async function()
{
	var params = {};
	
	params[1001] = {
					send:20,
					receive:30,
			};
			
	params[1002] = {
					send:300,
					receive:200,
			};
        client.register.removeSingleMetric("send");
	let sendCounter = new client.Gauge({
				name: "send",
				help: "send info",
				labelNames: ['hid']
			});
	sendCounter.labels(1001).set(params[1001].send);
	sendCounter.labels(1002).set(params[1002].send);
	
	client.register.removeSingleMetric("receive");
        let receiveCounter = new client.Gauge({
				name: "receicve",
				help: "receive info",
				labelNames: ['hid']
			});
	receiveCounter .labels(1001).set(params[1001].receive);
	receiveCounter .labels(1002).set(params[1002].receive);
	
	gateway.push( { jobName: 'host_stats' , groupings : { instance : ("push_server_1") , provider : 'nodejs'  }}, function(err, rep, body) {});
}
```
suppose that at second time, the values of host id  (hid)1001 are not changed / modified but the send and receive values of host id 1002 are changed and I wanna try to send just the data info of host id 1002 because I wanna try to optimize my data (it's so heavy in my application for all of hosts)
so I tried this:
```
const client = require('prom-client');
const gateway = new client.Pushgateway(config.prometheus_ip_port);

var mainFunc = async function()
{
	var params = {};
	
	params[1001] = {  //not changed
					send:20,
					receive:30,
			};
			
	params[1002] = { //changed
					send:500,
					receive:700,
			};
        client.register.removeSingleMetric("send");
	let sendCounter = new client.Gauge({
				name: "send",
				help: "send info",
				labelNames: ['hid']
			});
	//sendCounter.labels(1001).set(params[1001].send);
	sendCounter.labels(1002).set(params[1002].send);
	
        client.register.removeSingleMetric("receive");
	let receiveCounter = new client.Gauge({
				name: "receicve",
				help: "receive info",
				labelNames: ['hid']
			});
	//receiveCounter .labels(1001).set(params[1001].receive);
	receiveCounter .labels(1002).set(params[1002].receive);
	
	gateway.push( { jobName: 'host_stats' , groupings : { instance : ("push_server_1") , provider : 'nodejs'  }}, function(err, rep, body) {});
}

mainFunc();
```
the result diagram is broken for host 1001 but I wanna show it as not changed diagram by sending just modified data!
broken diagram is like below line, suppose that dashes are as constant diagram:
-----------             broken area until next sending modified data for 1001   -------------------
can I show joined (not broken) diagram without sending duplicated data?
even I have tried to use pushAdd instead of push method or do comment client.register.removeSingleMetric but noting's changed!
thanks a lot...

**Comment by zbjornson** [comment]
Not sure I entirely understand, but since Prometheus itself doesn't display data, I assume you're talking about Grafana. There's a setting there to connect gaps:

![image](https://user-images.githubusercontent.com/469365/76540479-ce9be400-6447-11ea-88f7-1f121d6ef856.png)
(*from https://community.grafana.com/t/gaps-in-the-display-of-data/5394/4*)
