### ISSUE TITLE
Proposal to add heapTotal and heapUsed to default metrics

### ISSUE THREAD

**Issue by jsha** [siimon/prom-client#35]
I've been using @SimenB's code to collect production stats for a few days now. I also manually added heapTotal and heapUsed stats to my app.

![heap-total-screenshot](https://cloud.githubusercontent.com/assets/220205/18418944/1fb1748c-7805-11e6-939c-b92ff3c9a02e.png)

As you can see, heapTotal and heapUsed are very different values than process_heap_bytes, and I think they more accurately reflect a typical understanding of heap usage. They also correspond to the value of `--max_old_space_size`. For instance, if I set `--max_old_space_size=400`, the process terminates when heapUsed (or heapTotal - haven't looked in detail) reaches 400MB. process_heap_bytes starts at ~1.4GB for my app.

@siimon, any objections to adding heapTotal and heapUsed as default metrics?

**Comment by siimon** [comment]
No objections really - as long as we make it clear for those who are used the lib what metric that shows what.. But that's maybe self explanatory?

**Comment by SimenB** [comment]
👍 from me, we have that at work in our own wrapper

**Comment by siimon** [comment]
@jsha any progress on this?

**Comment by siimon** [comment]
Fixed and published in 4.1.0! Let me know if anything doesn't work as expected - I'm away from work so I don't have any chance to test this in production myself.

**Comment by jsha** [comment]
Excellent, thanks! Sorry I didn't get to this as quickly as I thought I would.
