### ISSUE TITLE
collectDefaultMetrics and clearInterval

### ISSUE THREAD

**Issue by guyellis** [siimon/prom-client#352]
The Readme in the repo says:

> collectDefaultMetrics returns an identification when invoked, which is a reference to the Timer used to keep the probes going. This can be passed to clearInterval in order to stop all probes.

But in the code nothing is returned:

https://github.com/siimon/prom-client/blob/f57e932d60adda7447057963be98b61c143ecded/lib/defaultMetrics.js#L36

It's also typed with a `void` return: https://github.com/siimon/prom-client/blob/f57e932d60adda7447057963be98b61c143ecded/index.d.ts#L584-L586

**Comment by zbjornson** [comment]
Thanks for spotting that. The docs are out of date, will fix!

**Comment by guyellis** [comment]
@zbjornson - I'd be happy to PR the changes. How does one "clearInterval" now? I can update docs with answer.

**Comment by zbjornson** [comment]
Awesome. There is no way anymore to stop the default metrics (aside from calling `register.removeSingleMetric` for each of them). If that's functionality you need, we can come up with a replacement.

**Comment by guyellis** [comment]
No - that's good - I was just confused. I found the change: https://github.com/guyellis/prom-client/blob/master/CHANGELOG.md#1200---2020-02-20
