### ISSUE TITLE
Feature request: expose getValue() in public API

### ISSUE THREAD

**Issue by dobesv** [siimon/prom-client#367]
Today I thought I surely could pull metrics OUT of a Guage, but we're using TypeScript and the API doesn't declare any method of getting the current value out.  This means if I want those same numbers for my own purposes I have to use a private API.

It would be great if there was a public api `get(labels)` or `getValue(labels)` which returns the current value (if any) for a given label set.

**Comment by dobesv** [comment]
Actually, I think what would be best is to just declare the `get()` API that is there as-is.  Currently I'm just hacking it using that private API but it would be nicer if it were a public API.

**Comment by siimon** [comment]
I don't think this fits within this module, in that case I would probably create a module on top of `prom-client` that tracks this and also increments metrics in `prom-client`. The purpose of this library is to have metrics support for Prometheus, not a generic metric library.
