### ISSUE TITLE
Metrics prefix without collecting default metrics

### ISSUE THREAD

**Issue by shahvicky** [siimon/prom-client#371]
Hi all,
Currently if we want a prefix for all metrics, we have to pass it to the collectDefaultMetrics like
```
collectDefaultMetrics({ prefix });
```
Is there a way to have prefix for metrics without collecting default metrics. 
There is a `register. removeSingleMetric()`, which I can use to remove those default metrics but is there any other way?

**Comment by zbjornson** [comment]
I'm not sure I understand what you're looking for. The prefix setting only applies to default metrics. If you want a prefix on custom metrics, can you just prepend that prefix to the metric names?

**Comment by shahvicky** [comment]
yeah, you're right. I may have misunderstood the functionality. closing this
