### ISSUE TITLE
Why was timestamp support removed?

### ISSUE THREAD

**Issue by jdziat** [siimon/prom-client#376]
Hi Guys,
Love the library and i use it often. Just wondering why the timestamp value for metrics were removed(#333). Is this a best practice? I don't see it mentioned anywhere in https://prometheus.io/docs/instrumenting/exposition_formats/. If someone kept polling an endpoint and the time wasn't changing i would think that would indicate an error and something you should alert on. You can configure prometheus to ignore those timestamps if necessary in your environment as well.  

example:
```js
metric.set({}, 0, new Date())
```

**Comment by zbjornson** [comment]
There's an explanation in #177 from one of the Prometheus core maintainers.
