### ISSUE TITLE
Node app crashes for cluster_metrics API

### ISSUE THREAD

**Issue by parthg13** [siimon/prom-client#382]
Hi,
I am trying to implement cluster metrics using AggregatorRegistry. Earlier I tried it in my node application but after accessing the cluster_metric endpoint I used to get a blank response. So to understand how to implement it, I cloned the prom-client repository and tried running the cluster.js example which is included in the repo. But after accessing the cluster_metric on port number 3001, the app crashed with  **TypeError: metrics.forEach is not a function**. 

![Screenshot 2020-07-31 at 11 29 30 AM](https://user-images.githubusercontent.com/46792691/89005031-1d77e680-d321-11ea-94a3-be4a0b6e49f0.png)

If anyone could please help me to find out what's going wrong.
Thanks.

**Comment by zbjornson** [comment]
Sorry about that, it's fixed in the above PR (#384).

Note that the version of prom-client that you cloned from GitHub isn't a published released yet, so if you're installing it from npm in your real application, you'll have a different version.
