### ISSUE TITLE
Failed cluster worker resets counter values in AggregatorRegistry

### ISSUE THREAD

**Issue by DenisVoloshin** [siimon/prom-client#385]
We have the app which is running in a cluster mode.

Using the recommended way to collect metrics from all workers

```
const AggregatorRegistry = require('prom-client').AggregatorRegistry
const registry = new AggregatorRegistry()

const requestsCounter = new Prometheus.Counter({
    name: 'request_counter',
    help: 'request_counter',
    labelNames: ['platform', 'env']
});

```

The problem we run into happens when one of the workers fails.
Then a very unexpected thing happens, the failed worker resets its counter value in the AggregatorRegistry to zero.

It leads to the series of anomalies in the Grafana grash, especially all rate based graphs. 
I would expect the AggregatorRegistry is able to run in kind of the cache mode, when the AggregatorRegistry stores the state of stopped woker's count values. If AggregatorRegistry doesn't support such a mode. Is there any simple workaround to cope with this limitation. thanks

**Comment by zbjornson** [comment]
This is a more general issue in the sense that all metrics reset when the app restarts; there is no persistence layer. #364 has some info.

**Comment by zbjornson** [comment]
Closing per above.
