### ISSUE TITLE
How to specify aggregation without instance?

### ISSUE THREAD

**Issue by shzmilydahlke** [siimon/prom-client#389]
<aggr-op> [without|by (<label list>)] ([parameter,] <vector expression>)
sum without (instance) (http_requests_total)

I have a gauge with config : 
gauge({
    name : 'redeem_codes_remaining',
    labelNames : ['key','service'],
    aggregator: 'min'
}
When we spin up multiple EC2s, a time series is created per instance. How can I specify 'without (instance)' in the aggregaror?

btw I got around the problem by specifying this in grafana, but still wondering if there is a programmatic option:
min(redeem_codes_remaining {env="prod"}) without (instance)

**Comment by zbjornson** [comment]
I'm not exactly sure what you mean. Each EC2 instance should be scraped independently by prometheus, and then you can "aggregate" (summarize) them with PromQL/Grafana/etc., like what you're doing in the last line of your post. The aggregator is for combining multiple cluster workers running on a single EC2 instance.

**Comment by zbjornson** [comment]
Closing for now per above, but happy to reopen if you provide more info.
