### ISSUE TITLE
Require fails when run in a process without stdin

### ISSUE THREAD

**Issue by Noah-Huppert** [siimon/prom-client#391]
# Overview
I have a Linux 5.4 server which I am running a NodeJS expressjs app on. This app uses `prom-client`.

If I run the app in an interactive terminal everything works fine. However if I run the app in the background it crashes. If I remove `require('prom-client')` (and only this) my app works fine in the background.

It looks like `prom-client` is trying to read stdin on import, and is failing, thus crashing my process.

# Expected Behavior
When I run my NodeJS application without any stdin (in a non-interactive terminal) it should work.

# Actual Behavior
When I run my NodeJS application without any stdin it crashes with the error:

```
+ exec node index.js
hello world
events.js:291
       throw er; // Unhandled 'error' event
       ^
 Error: read ENOTCONN
     at tryReadStart (net.js:574:20) 
     at ReadStream.Socket._read (net.js:585:5)
     at ReadStream.Readable.read (_stream_readable.js:475:10)
     at ReadStream.Socket.read (net.js:625:39)
     at ReadStream.Socket (net.js:377:12)
     at new ReadStream (tty.js:58:14)
     at process.getStdin [as stdin] (internal/bootstrap/switches/is_main_thread.js:151:15)
     at get (<anonymous>)
     at getOwn (internal/bootstrap/loaders.js:150:5)
     at NativeModule.syncExports (internal/bootstrap/loaders.js:258:31)
	 Emitted 'error' event on ReadStream instance at:
     at emitErrorNT (internal/streams/destroy.js:100:8)
     at emitErrorCloseNT (internal/streams/destroy.js:68:3)
     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
	 errno: -107,
	 code: 'ENOTCONN',
	 syscall: 'read'
}
```

# Details
I have isolated the cause of the crash to `require('prom-client')`. If I don't have this require statement in my app everything works fine.

[Here is a 2 line self contained example](https://github.com/Noah-Huppert/bugs/tree/master/nodejs-prom-client).

It seems like the program is getting the error `ENOTCONN` on a `read` system call for the `stdin` file descriptor.

The fix to this error is to pipe some sort of stdin to the process in the background:

```
: | node index.js
```

**Comment by SimenB** [comment]
I've never seen something like this 😅 @sam-github you wouldn't happen to have any ideas, would you?

**Comment by sam-github** [comment]
node has to have _something_ on fd 0 ("stdin"). Traditionally init system run services with /dev/null attached to stdin, and stdout and err redirected to a system logger. No idea what runit does, and no time to figure it out. try `exec node blah.js < /dev/null`.

**Comment by Noah-Huppert** [comment]
Yea I just have the run script pipe the source code file into node 😆: exec
node index.js < index.js

My thought is there's probably some dependency of prom-client that's
reading stdin.

**Comment by SimenB** [comment]
`grep`ing in `node_modules` when excluding dev dependencies shows no `stdin` anywhere. `prom-client` itself does not touch `stdin` either. The stack comes from node core itself though so we might indirectly trigger it via loading some module (`cluster`, `perf_hooks` or something else)?

**Comment by zbjornson** [comment]
I don't see where this issue could arise either, especially since this is coming from the net built-in module. Running `node -e "process.stdin=null; console.log(require('.'))" 0<&-` in my prom-client dev directory on Ubuntu works. Closing to clean up issues, but please comment if you have more info.

**Comment by Noah-Huppert** [comment]
@zbjornson understandable I feel like something downstream from you is causing this issue. Hopefully the workarounds we've both posted will help anyone who comes across this from google 😃

**Comment by edwardofclt** [comment]
Came across this today and this solved my issue. Thanks for this.
