### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by PhilThurston** [siimon/prom-client#396]
Other libraries we've used like with Go support basic auth for a push gateway that is setup with basic auth as per the Prometheus documentation. https://prometheus.io/docs/guides/basic-auth/

Is there any interest or plans for implementing a way to pass creds to a pushgateway that has authentication enabled?

**Comment by zbjornson** [comment]
I think you can already do this by passing `auth: "username:password"` into the setup:

```js
const gateway = new client.Pushgateway("http://127.0.0.1:9091", {auth: "username:password"})
```

That second object corresponds to the `options` object for [`http.request`](https://nodejs.org/dist/latest-v14.x/docs/api/http.html#http_http_request_options_callback).
