### ISSUE TITLE
Browser metrics

### ISSUE THREAD

**Issue by VoidMonk** [siimon/prom-client#398]
Hi,

I'm trying to figure out if Prometheus and prom-client are a possible way to record browser metrics of website visitors.

I can have a Nodejs server script (with prom-client), that a webpage can request (HTTPS GET or POST) to submit the visitor data, but I'm not sure how to record the bare minimum metrics (with prom-client) needed for each website visit, mainly:

* Date-time of visit
* Site name (to separate metrics by site)
* Page (text/string URL of visited page on site)
* Counter for total views (number) for given page and site

I'll appreciate if someone can share their suggestions or tips.

Cheers!

**Comment by zbjornson** [comment]
This question is probably better suited to StackOverflow or the [prometheus user group](https://groups.google.com/forum/#!forum/prometheus-users), but briefly: Most of those are more like log-oriented data, which is not what Prometheus is designed for. Prometheus metrics aren't suitable for observing values that don't repeat, so you could track time of day of visits, but not the date. You could use a Counter for the last bullet point. Site name could be recorded using a label.

Closing to clean up issues but happy to continue discussing.
