### ISSUE TITLE
clear out a metric in prometheus

### ISSUE THREAD

**Issue by aeyuxi** [siimon/prom-client#402]
I'm currently using a platform to store orders that changes through time. I'm using Prometheus to also scrape when an order is created or when it changes its status. Find an example of the object below.

`order = {id: <id>, status : <ORDERED, LOADED, DELIVERED>, time: <time>}`

In order to save the order into Prometheus, I'm doing the following.

`prom_order.inc(order)`

I'm currently using a counter. However, after some a while, the metrics API keeps tracks of very old records. Also, Prometheus will save orders with the same id and the different statues. So, if the order went from **ORDERED** to **DELIVERED**, it will appear 3 different times. I'm wondering if there is a better metric to use for this case. Probably a metric that only preserves the last state? Maybe a metric that goes to zero? Is there a metric that can be reset when is no longer needed? Is it possible maybe to delete or decrease a metric based on one of the _labelNames_?

**Comment by zbjornson** [comment]
This question is probably better suited to StackOverflow or the [prometheus user group](https://groups.google.com/forum/#!forum/prometheus-users). My understanding is that clearing a metric is an anti-pattern in Prometheus, and we don't have an API for that in this library. What you described might be better achieved with log-oriented data or a plain database query.

Closing to clean up issues, but happy to keep discussing.
