### ISSUE TITLE
Docs - What Gauge.startTimer is for?

### ISSUE THREAD

**Issue by stavalfi** [siimon/prom-client#405]
After asking and there was no answer in:

* stackoverflow: https://stackoverflow.com/questions/64445376/what-is-gauge-starttimer-for-and-how-to-properly-use-it 
* promethues mailing list: https://groups.google.com/g/prometheus-users/c/ckTn7pEtujw, 

I'm asking here the same question. Maybe this should be added to the docs as well.

-----

As I understand, the `Gauge` counter is a value that changes over time ___without___ saving somewhere when every change of the counter (`dec(x)` or `inc(y)`) was and the labels of every call to `dec` or `inc`.

Please correct me if I'm wrong.

# Questions

* What exactly `Gauge.startTimer` does?
* What will be sent to prometheus?
* When to use it?
* How does it saves the data locally in my application?

**Comment by zbjornson** [comment]
It's a utility function to help record durations that are kept in a gauge. There's an example usage in the docs: https://github.com/siimon/prom-client#utility-functions

```js
// Record durations:
const end = gauge.startTimer();
http.get('url', res => {
  end();
});
```

>  the Gauge counter is a value that changes over time without saving somewhere when every change of the counter (dec(x) or inc(y)) was

Correct, that'd be more like a histogram or summary (both of which also have `startTimer()` utilities). It's probably most useful for recording something that doesn't change very often for that reason, but I'm sure there are some other interesting uses for it.

Data is stored internally in the gauge, then prometheus should scrape it.

**Comment by zbjornson** [comment]
(Closing to clean up issues, but happy to keep discussing.)
