### ISSUE TITLE
Bump and publishing new version

### ISSUE THREAD

**Issue by andymost** [siimon/prom-client#408]
Hi, @siimon! Can you bump version of package and publish new version at npm if everything ok? 
Really waiting for collect method for metrics, thanks in advance.

**Comment by samkelleher** [comment]
Yeh +1, just been coding using the collect method, as it's documented, after debugging for hours since it's not working, realised that it's simply not published. The collect system looks really useful so great to get hands on it. 🤗🤗🤗🤗🤗

**Comment by siimon** [comment]
Sorry about that, real life has not allowed me to work on this project for quite some time.. I just published 13.0.0
