### ISSUE TITLE
The "chunk" argument must be one of type string or Buffer. Received type object

### ISSUE THREAD

**Issue by ionalexandrusecara** [siimon/prom-client#414]
Hi!

I'm getting the following error whenever I try to access the `/metrics` endpoint.

`TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object`

This is how the `/metrics` endpoint looks like:
![image](https://user-images.githubusercontent.com/15220854/102418519-bd719c00-3fb2-11eb-9c11-d482e7607c96.png)

Would appreciate any feedback on this.

**Comment by lunae** [comment]
Ran into the same issue. I believe the solution is found in the release notes for `13.0.0`. https://github.com/siimon/prom-client/releases/tag/v13.0.0. `metrics()` now returns a promise. In your example, the fix would be to make the handler async and await the call to `metrics()`. It was a breaking change in `13.0.0`. Hope that helps!

```
app.get('/metrics', async (req, res) => {
  res.set('Content-Type', prometheus.register.contentType)
  res.end(await prometheus.register.metrics())
})
```

**Comment by mrcampbell** [comment]
Thank you @lunae!!!
