### ISSUE TITLE
Advanced event loop monitoring not aggregated correctly across cluster

### ISSUE THREAD

**Issue by mkreidenweis-schulmngr** [siimon/prom-client#418]
Hi everybody, 

could it be the the cluster support (#147) was overlooked when introducing the advanced event loop monitoring in #278?

The old event loop metric has an `aggregator` set, whereas all the new onen don't: 
https://github.com/siimon/prom-client/blob/c63689bbbb6a0395ce9d806b0cc17cf5d380f4a8/lib/metrics/eventLoopLag.js#L37

Was looking at some metrics of a node cluster today and couldn't quite make sense of it. It looks to me like something else than the default `sum` aggregator should be used for most the other lag metrics, right?

**Comment by zbjornson** [comment]
Opened #422 if you'd like to give it a try or provide feedback!

**Comment by mkreidenweis-schulmngr** [comment]
Thanks for having looked into this. This actually went down in our priorities, as we actually moved away from using node cluster module. It also caused other problems with Prometheus metrics, e.g. causing random spikes in metrics when single cluster processes were restarted -- `increase()` and `rate()` can't deal with that properly. So it looks like I won't make time to try it out.

Maybe somebody else wants to give it a try? @dominathan seemed to be interested. :-)
