### ISSUE TITLE
Question about metric size

### ISSUE THREAD

**Issue by scramble45** [siimon/prom-client#420]
I have prom-client integrated into my app exposing a `/metrics` route. This route exposes a histogram metric with various HTTP request durations from many different requests going through our API. My question is how big can this grow before it becomes problematic? Does prom-client self manage the size of what comes out of the `/metrics` route? Basically I am just trying to mitigate a potential memory leak as the amount of requests we do is pretty crazy. Do these exposed metrics get reset outside of restarting the application?

**Comment by zbjornson** [comment]
I don't know of a general guideline for that, but nothing should actually leak and the internal representations are pretty compact. I haven't seen any issues in this repo about memory usage.

Metrics don't get reset, and as far as I understand, that would be a Prometheus antipattern.
