### ISSUE TITLE
Why is there such a big difference in the process_resident_memory_bytes and docker stats?

### ISSUE THREAD

**Issue by budarin** [siimon/prom-client#424]
Docker stats - 20Mb
process_resident_memory_bytes - 57mb

OS: Mac
Docker Desktop for Mac

**Comment by zbjornson** [comment]
This is more of a docker question. This lib just reports `process.memoryUsage`'s output. https://stackoverflow.com/questions/66607128/docker-stats-show-memory-usage-less-than-output-of-top-command might have useful info.
