### ISSUE TITLE
Counter.get() not recognised in Type Script

### ISSUE THREAD

**Issue by ramiloif** [siimon/prom-client#425]
Here is my code: 
```
async function test() {
  const c: Counter<"some"> = new Counter({
    name: "test",
    help: "",
    labelNames: ["some"]
  });

  const data = await c.get();
}
```

And here is the ts compilation error: 
`error TS2339: Property 'get' does not exist on type 'Counter<"some">'.`

**Comment by david-winder-kaltura** [comment]
I think this fixed that: https://github.com/siimon/prom-client/commit/081d8a0f7ebf287ae6e442247467d5cc7ae6d4db

**Comment by SimenB** [comment]
indeed, thanks! 🙂
