### ISSUE TITLE
Dash/hypen in the label name?

### ISSUE THREAD

**Issue by dpc** [siimon/prom-client#427]
It seems like it's currently consider invalid, and I used these in other projects in other programming languages.

**Comment by zbjornson** [comment]
The prometheus docs say:

> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex `[a-zA-Z_][a-zA-Z0-9_]*`. Label names beginning with __ are reserved for internal use.

https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

Assuming the docs are correct, it sounds like the other language clients are incorrect in allowing dashes.

**Comment by dpc** [comment]
Thanks. Good to know.
