### ISSUE TITLE
Improper syntax for try..catch statements

### ISSUE THREAD

**Issue by jadonk** [siimon/prom-client#428]
There are numerous try..catch statements that look like:

```
try {
  // stuff
} catch {
  // more stuff
}
```
These aren't proper JavaScript syntax.  See http://es5.github.io/#x12.14.

Use:
```
try {
  // stuff
} catch(e) {
  // more stuff
}
```

**Comment by jadonk** [comment]
Found https://github.com/siimon/prom-client/commit/af298afeafaf8bb06cbcea23c4814a9dbc434a8a

Guess I'm using an older version of node, but why cause this to break?

**Comment by zbjornson** [comment]
That's [optional catch binding](https://v8.dev/features/optional-catch-binding), supported by Node.js v10+. All versions of Node.js lower than 10 are EOL and don't receive security updates. We track with their releases. If you need support for older versions of Node, you can install older versions of this library.

**Comment by jadonk** [comment]
OK, thanks.
