### ISSUE TITLE
prom-client return empty object

### ISSUE THREAD

**Issue by khanveerr** [siimon/prom-client#430]
Hi Team,

I am having issues with prom-client. As it returns a blank object when I hit metric URL.

Below is my code

```
import { Registry, collectDefaultMetrics  } from "prom-client";

const register = new Registry();
collectDefaultMetrics({ register: register });

export default (req, res) => {
    register.clear()
    res.setHeader("Content-type", register.contentType);
    res.send(register.metrics());
};

```

When I try to access the metrics URL it returns a blank object. The screenshot below for reference.

![image](https://user-images.githubusercontent.com/13793680/110925258-f8346780-8348-11eb-97d9-c7c78b9f11a5.png)

And the Prometheus target state is down. The screenshot below for reference

![image](https://user-images.githubusercontent.com/13793680/110925428-2dd95080-8349-11eb-8ba9-36a58512ae11.png)

I don't understand where I am wrong.

**Comment by zbjornson** [comment]
`register.metrics()` returns a Promise, try `await register.metrics()`. You also shouldn't be calling `register.clear()` in your Prometheus scraping endpoint; that removes all metrics.
