### ISSUE TITLE
How to get list of all labels from metric instance?

### ISSUE THREAD

**Issue by budarin** [siimon/prom-client#433]
Unfortunately, the metrics themselves can not select the labels they need from the labels object provided to them during the call and pass everything that will be in this object to the metric.

```
const clientErrors = new Counter({
    name: `${defaultOptions.prefix}client_errors_total`,
    help: 'Counter for clients errors',
    labelNames: ['type', 'pathname'],
});
....
const commonLabels = {
  type: 'someType',
  pathname: location.pathname,
  os: 'IOS',
  date: new Date()
}
...
clientErrors.inc(commonLabels); <- there will be an error!!!
```

(It would be great if metric could independently select the labels it needs from the labels object and would not give an error about extra labels)

Is it possible to get a list of the labels specified in the metric constructor?

**Comment by zbjornson** [comment]
> Is it possible to get a list of the labels specified in the metric constructor?

Yes, `mymetric.labelNames` is the array of label names.
