### ISSUE TITLE
[Feature]: Histogram support for automatically created buckets. 

### ISSUE THREAD

**Issue by SkeLLLa** [siimon/prom-client#434]
The details are covered in following topic:

https://valyala.medium.com/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350

Those metrics are quiet similar to Prometheus histograms, but allows some additional features.

**Comment by zbjornson** [comment]
It looks like that only works with remote write to VictoriaMetrics:

> Unfortunately this query doesn’t work in Prometheus, since it is unaware of VictoriaMetrics histograms yet. So set up VictoriaMetrics as a remote storage for Prometheus according to these simple docs and enjoy the power of user-friendly histograms. Or just use vmagent for sending data to VictoriaMetrics.

Until that's supported in Prometheus, it's probably best to implement it as a custom metric type (`class VMHistogram extends Metric`). We don't support remote write yet either: #445.
