### ISSUE TITLE
How to push just custom metrics and not the default metrics using PushGateWay

### ISSUE THREAD

**Issue by KunalBurangi** [siimon/prom-client#451]
Here is the use case,
There are two types of metrics

Default metrics
Custom Metrics
what I want to do is just want to push the custom metrics via push gateway and not the default metrics. can we do that?
if yes how?

I have tried to use the registers, but how do view values of different registers?
or can we push metrics from a particular register?

is there any way to solve this use case?

**Comment by ValorHeart** [comment]
Hey, Did you find answer for that question?

**Comment by zbjornson** [comment]
Does omitting `collectDefaultMetrics()` do the trick?

**Comment by ValorHeart** [comment]
@zbjornson No it did not help, here is the reproduce code:
```
import * as prom_client from 'prom-client';
import {Gauge} from 'prom-client';

(async () => {
    const customRegister = new prom_client.Registry();

    const someMetric = new Gauge({
        name: 'some_metric',
        help: 'Help for some meric',
        labelNames: ['project'] as const,
        registers: [],
    });
    someMetric.set({project: 'prometheus'}, 10);

    customRegister.registerMetric(someMetric);
    
    const pushgatewayClient = new prom_client.Pushgateway('http://localhost:8080', customRegister);
    await pushgatewayClient.pushAdd({jobName: 'some_job'});
})();

```
