### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by artificial-aidan** [siimon/prom-client#454]
A number have changes have gone in since the last release. What is the process for cutting a new release? Are most people just installing from git?

**Comment by zbjornson** [comment]
I'm planning to make one shortly, just one more PR I need to review that I think is ready to land.

**Comment by artificial-aidan** [comment]
Much appreciated.

**Comment by zbjornson** [comment]
[v13.2.](https://github.com/siimon/prom-client/releases/tag/v13.2.0) is now published, thanks for your patience.
