### ISSUE TITLE
Some questions for better understanding

### ISSUE THREAD

**Issue by AhmedBHameed** [siimon/prom-client#463]
Hi,

I'm new to `Prometheus`. Thank you for the nice work!

I have a few questions in comparison to S*n*try performance monitoring service.

![questions](https://user-images.githubusercontent.com/25675361/133925646-a4bf655d-021b-477b-9fd1-69a37213df5b.png)

In S*n*try service, they have a nice documentation of monitoring API performance. I have a graphql here and from what we see, this is a single resolver metric.

- From number (1), I managed to get the time metric for a single resolver including the time for frequent calls.
- In (2), is there a way to provide tags to distinguish between development and production environments?
- In (3), another nice feature, is that collecting resolver keys as a tree. It is called `span` and they also a nice metric to see. How can we do that with `prom-client`?
- In (4), the http APIs are intercepted by default. That is a nice sandbox feature. I know there is something called `collect` which can do this but, it is a bit applicable individually? (not sure).
- Something from my side, I applied a pull route to collect data, is there a way to push to the Prometheus server? I think that would make more sense in my scenario.

In general, I managed to collect time metric and resolver frequent calls which are the most important from my perspective, but they are a bit hard to debug when details required.

![sample](https://user-images.githubusercontent.com/25675361/133925973-d2aff44c-cd75-4c0a-9946-22b8ec02a9f6.png)

**Comment by zbjornson** [comment]
Most of these questions are probably better suited to the Prometheus community forums: https://prometheus.io/community/. It looks like you want to do tracing, which is not what Prometheus does though. Grafana, which is commonly used with Prometheus, can serve as the front end for tracing, see https://grafana.com/blog/2021/01/25/a-beginners-guide-to-distributed-tracing-and-how-it-can-increase-an-applications-performance/.
