### ISSUE TITLE
histogram startTimer typescript definition

### ISSUE THREAD

**Issue by dragoscirjan** [siimon/prom-client#465]
Hello,

Under: https://github.com/siimon/prom-client/blob/master/index.d.ts#L390, you have 

```typescript
/**
	 * Start a timer where the value in seconds will observed
	 * @param labels Object with label keys and values
	 * @return Function to invoke when timer should be stopped
	 */
	startTimer(labels?: LabelValues<T>): (labels?: LabelValues<T>) => number;
```

while all other `startTimer` functions are defined as

```typescript
/**
	 * Start a timer where the value in seconds will observed
	 * @param labels Object with label keys and values
	 * @return Function to invoke when timer should be stopped
	 */
	startTimer(labels?: LabelValues<T>): (labels?: LabelValues<T>) => void;
```

Is there any reason for this?

**Comment by zbjornson** [comment]
Neither of those are correct, thanks for pointing it out. I can fix it this week, also happy to review a PR if you want to make one.

**Comment by zbjornson** [comment]
I misread: both of those are correct. I don't know why only histograms return the duration, but I opened a PR to make gauges and summaries consistent with histograms: #466.

**Comment by zbjornson** [comment]
Will be in the next release!
