### ISSUE TITLE
Scrapping logic extextion

### ISSUE THREAD

**Issue by KunalBurangi** [siimon/prom-client#467]
Is there any function that can help in extending the scraping logic of Prometheus?
so that i and add some extra logic as per my project requirement. 
OR 
is there any way where my metric value should get null after it has been scraped once?

**Comment by zbjornson** [comment]
I'm not sure what you're asking in the first part of your question, but that sounds like a Prometheus question and not a prom-client question.

Prometheus metrics aren't intended to be reset after scrapes. Instead, Prometheus provides functions to e.g. calculate deltas between scrapes. You could look at PushGateway though, not sure what your use case is.
