### ISSUE TITLE
Calling pushgaetway functions still requires passing 2 arguments (args and callback)

### ISSUE THREAD

**Issue by Landria** [siimon/prom-client#468]
Pushgateway got promisified In v14.0.0, but it still requires a callback when you call it.
It comes from here: https://github.com/siimon/prom-client/blob/5c1c68e1eca3d9a47d615e18f130aed7fae7c011/index.d.ts#L564

**Comment by SimenB** [comment]
Wanna send a PR fixing it? 🙂

**Comment by SimenB** [comment]
https://github.com/siimon/prom-client/releases/tag/v14.0.1
