### ISSUE TITLE
Release new version with fixed typings

### ISSUE THREAD

**Issue by TheDadi** [siimon/prom-client#473]
Hi to all 🤝 

Since the merge of (Update pushgateway type def (#469)) this package got no new release.
Could you please release a new version with the fixed typings.

Thx

**Comment by sonnen-athene** [comment]
Also running into issues because of this. Any ETA on a release?

**Comment by Ghazgkull** [comment]
@adilhafeez Are you able to help with this? It looks like the package version wasn't updated when your PR was merged, so the new type definition isn't available.

**Comment by Ghazgkull** [comment]
@TheDadi Looks like a new release is up now with the new type bindings! v14.0.1!
