### ISSUE TITLE
Support of unicode symbols in a label value

### ISSUE THREAD

**Issue by WoZ** [siimon/prom-client#493]
I've found that validation.js's method `validateLabelName` restricts usage of any unicode characters. Despite this, prometheus allows any unicode characters. [Quote](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels):

> Label values may contain any Unicode characters.
> A label with an empty label value is considered equivalent to a label that does not exist.

https://github.com/siimon/prom-client/blob/98b7ad819978436b19a994bb5c9f7bcf7576578a/lib/validation.js#L5-L15

Is there any reason why unicode was restricted? Thank you.

**Comment by zbjornson** [comment]
I just checked: label values do support any character. The code you linked to is used to validate label *names*, not values.
