### ISSUE TITLE
Allow global namespace to be define

### ISSUE THREAD

**Issue by kaareal** [siimon/prom-client#51]
It would be useful if you could define a global namespace => a prefix to be attach to all metrics names.

**Comment by SimenB** [comment]
All, or just new ones after you register your default?
All would mess up some standard metrics (https://prometheus.io/docs/instrumenting/writing_clientlibs/#standard-and-runtime-collectors)

**Comment by kaareal** [comment]
Yeah, good point. I guess just new ones.

**Comment by SimenB** [comment]
The thing is that as this library works as a singleton, you then modify this for everyone in the tree using metrics. If it's an app, sure, but a library exposing metrics shouldn't have its names changed from underneath even if they're registered async.
And if we make it opt-in, why not just prefix the stuff you want at creation time?

**Comment by siimon** [comment]
Think @SimenB has good points, and I'm not sure there is a good way to fit it into the current prom client functions either. 

Im not really sure what's the most common use case in the wild, but at work we don't prefix metric names with a namespace, we have it in a label instead so thats why I didn't include it in this lib.

**Comment by kaareal** [comment]
Thanks for you feedback.
I am gonna go ahead and close and do as @SimenB suggested.
