### ISSUE TITLE
Active handles doesn't retrieve all handles

### ISSUE THREAD

**Issue by mkadirtan** [siimon/prom-client#529]
I'm using eiows with socket.io, which is a C based websocket library. The active_handles count is almost 0 even though there are open websocket connections, but if I switch back to ws library it shows active_handles count correctly. I've tried to investigate how can I retrieve them, but no luck. Do you have a suggestion or a fix for this?

Related issue on eiows: https://github.com/mmdevries/eiows/issues/13

**Comment by SimenB** [comment]
We just use a node API: https://github.com/siimon/prom-client/blob/8d6456c05f0708fed34628da5bd6f492a0ab43f8/lib/metrics/processHandles.js#L27

So if your handle doesn't show up I'd open an issue either with the lib you use (as you've done) or with node itself.

**Comment by mkadirtan** [comment]
Thanks for the reply. Actually, I realized active handles is not the correct metric for open socket connections. The open file descriptors give accurate results 🎉
