### ISSUE TITLE
counter.inc(0) shouldn't increase

### ISSUE THREAD

**Issue by haraldschilly** [siimon/prom-client#53]
I've a case here, where I'm counting up integers which can also be zero. So, it might happen that `counter.inc(0)` is called and I assumed, that this doesn't increase it. As far as I can see, this boils down to `value || 1` → `1`, for `value == 0, at the bottom of counter.js.

Right there, I would rather just skip calling the counter if the value is zero.

**Comment by siimon** [comment]
Thanks, fixed in 5.0.3

**Comment by haraldschilly** [comment]
Wow, this was quick :-)

BTW, and I should probably open a second ticket, this `value || 1` also appears twice here https://github.com/siimon/prom-client/blob/master/lib/util.js#L12 in `incValue`. Not sure about the context where it is used, though. I think, the super-correct way of checking this would be an if/else testing `typeof value !== "undefined" && value !== null`
