### ISSUE TITLE
Provide `collect()` for Counters

### ISSUE THREAD

**Issue by debuglevel** [siimon/prom-client#534]
It would be nice to also have a `collect()` for `Counter`s.

This would be useful in two cases:

* I just do not use `prom-client` to collect my metrics, because e.g. I already had my own metrics stuff implemented. A `collect()` should just retrieve it.
* I (maybe misuse?) metrics/counters for long-running statistics like "How many users does this application have registered?" which likely will be retrieved from a database.

**Comment by zbjornson** [comment]
It exists already! :)

All metric types support it. I see now that the readme is sort of confusing in terms of where it documents `collect()` though.

**Comment by debuglevel** [comment]
I see. I might probably did not understand how this part works:
```
new client.Gauge({
  name: 'metric_name',
  help: 'metric_help',
  collect() {
    // Invoked when the registry collects its metrics' values.
    // This can be synchronous or it can return a promise/be an async function.
    this.set(/* the current value */);
  },
});
```

I misinterpreted of `this.set()` being some substitute for a `return` which just returns the current value to be exported; and therefore tried `this.set(123)` on a `Counter` which obviously does not work.

I thought `collect()` worked this way:
```
new imaginaryPromClient.Counter({
  name: 'metric_name',
  help: 'metric_help',
  collect() {
    return myDatabase.users.count;
  },
});
```
But I guess that's just not how things work :-)

**Comment by zbjornson** [comment]
Right, we don't use the return value because you might need to set one or more different labeled values (i.e. call `this.set()` multiple times with different labels).

**Comment by debuglevel** [comment]
Okay, I guess I would have to use something like `reset` and `inc(myValue)` to accomplish what I need for a `Counter` -- or just stay with a Pseudo-`Gauge` :)

I'm closing this issue, because that's probably just not how `prom-client` is intended to work :D

**Comment by debuglevel** [comment]
Just in case Google takes someone here:

```ts
    const foo_counter = new client.Counter({
        name: 'foo',
        help: 'TODO',
        collect() {
            this.reset();
            this.inc(foobar.count());
        },
    });
```

**Comment by zbjornson** [comment]
You're sure you don't want to use a Gauge?

**Comment by debuglevel** [comment]
To be honest, I don't even know whether there are real differences between Gauge and Counter in the end (my Prometheus stores it into some magical database, Grafana makes nice graphics, I'm happy). :)
But as I wanted to honor the OpenMetrics specs, I decided for a Counter (because this metric it only increases) just in case it actually does matter somehow :)

**Comment by zbjornson** [comment]
`reset()` might get removed at some point; it was probably a mistake to include it in the API. OpenMetrics supports Gauges, so I'd encourage trying that out.
