### ISSUE TITLE
Question: What is the window size which the Summary quantiles are calculated over?

### ISSUE THREAD

**Issue by ivarconr** [siimon/prom-client#55]
I can't find this anywhere in the documentation.

**Comment by siimon** [comment]
Good question, we are using TDigest (https://www.npmjs.com/package/tdigest) for calculating percentiles. We never set any window in prom-client so we are using the default behavior. What that default is, I'm not sure but my guess is infinite.

**Comment by ivarconr** [comment]
thanks. I will will read the TDigest paper. My first impression is that is looks clever!
