### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by chenhuanguang** [siimon/prom-client#567]
I would like to ask, is the indicator of prom-client stored in memory? I use prom-client and swagger-stats in my project. The interface for swagger-stats to obtain indicators is 'swagger-stats', while prom-client acquires indicators The interface is '/metrics', but I am calling /metrcis Why does it include swagger-stats indicators

**Comment by zbjornson** [comment]
I'm not sure what you're asking. Can you clarify please? How and where you expose prom-client's metrics is entirely up to you.
