### ISSUE TITLE
`Gauge.setToCurrentTime()` : TypeScript definition says the time is set in milliseconds, but implementation sets the time in epoch seconds

### ISSUE THREAD

**Issue by Totalus** [siimon/prom-client#568]
TypeScript doc says it sets the value to epoch milliseconds:

https://github.com/siimon/prom-client/blob/1df34ed58e83914244e8e6c99edc1e086697af5a/index.d.ts#L361-L365

Actual implementation sets the value to epoch seconds:

https://github.com/siimon/prom-client/blob/1df34ed58e83914244e8e6c99edc1e086697af5a/lib/gauge.js#L74-L86

I guess it was not updated properly after changed to seconds (#167)

**Comment by SimenB** [comment]
Wanna send a PR updating? 🙂
