### ISSUE TITLE
process_cpu_seconds_total increasing faster than 1/s

### ISSUE THREAD

**Issue by jsha** [siimon/prom-client#57]
I recently upgraded my services to Node 6 in order to start collecting process_cpu_seconds_total. I'm now graphing the results and seeing strange results. The stats seem to be claiming that Node is using 125k seconds per second, according to this Prometheus query:

```irate(process_cpu_seconds_total{job="bt-actions"}[1m]) * 60```

Screenshot of Grafana plot attached. Any idea what's up? Am I querying this wrong or using the wrong units? Do you have reports from people successfully using the process_cpu_seconds_total stat?

Thanks,
Jacob

![screenshot from 2016-11-03 09-30-37](https://cloud.githubusercontent.com/assets/220205/19975206/5a13ff24-a1a8-11e6-80c2-fd90dfe580e2.png)

**Comment by siimon** [comment]
I've not deployed it myself since I'm on parental leave, but it might happen if you have multiple cores, but it sounds abit much with 125k seconds in a second :)

@SimenB are you using that metric?

**Comment by SimenB** [comment]
We're using it, yeah. I won't have access to the query until Monday, but I can check it out then

**Comment by jsha** [comment]
Yeah, I don't have that many cores. :-) Also, Node shouldn't use more than one core per process since it's single threaded. Will look forward to your results @SimenB, thanks.

**Comment by SimenB** [comment]
Ok, took a look now, and it's definitely a bug. 

Trying to figure out why these print different diffs:

```js
'use strict';
​
let prevTotal = 0;
​
setInterval(() => {
    const usage = process.cpuUsage();
    const total = usage.user + usage.system;
    const diff = total - prevTotal;
    console.log(diff, 'curr diff');
    prevTotal = total;
    // console.log(total, 'total');
    console.log();
}, 250);
​
let previousUsage = process.cpuUsage();
let totalUsage = 0;
​
setInterval(() => {
    const diffUsage = process.cpuUsage(previousUsage);
    previousUsage = diffUsage;
    const diff = diffUsage.user + diffUsage.system;
    console.log(diff, 'diff with prev');
    totalUsage += diff;
    // console.log(totalUsage, 'total with prev');
    console.log();
}, 250);
```

**Comment by siimon** [comment]
@Blystad fix is merged and pushed in 6.1.1, @jsha can you confirm that the fix resolves your issue?

**Comment by SimenB** [comment]
This resolves our issue.

![image](https://cloud.githubusercontent.com/assets/1404810/20104627/faded454-a5ce-11e6-90cb-a4e09b15a852.png)

**Comment by siimon** [comment]
Closing this issue then :)
