### ISSUE TITLE
Is it possible to use in Bun/Deno/other runtime?

### ISSUE THREAD

**Issue by krutoo** [siimon/prom-client#570]
Hi, currently i use prom-client in nodejs app and want to use it in other runtime such as Deno or Bun

Is it possible today?

**Comment by SimenB** [comment]
I dunno. We use a bunch of node specific APIs, but mostly in the default metrics. I guess you could omit them?

I've never used either Deno or Bun, so you'd have to tell us and potentially send PRs for changes needed 🙂

**Comment by krutoo** [comment]
Yes, node and v8 specific default metrics can be omitted

**Comment by zbjornson** [comment]
@krutoo if you want to test my PR, that would be helpful: `bun install siimon/prom-client#zb/bun`.

**Comment by dawidsowardx** [comment]
> Yes, node and v8 specific default metrics can be omitted

@krutoo How? Is it documented anywhere

**Comment by krutoo** [comment]
> > Yes, node and v8 specific default metrics can be omitted
> 
> @krutoo How? Is it documented anywhere? I want to omit metric by metric

@dawidsowardx I mean in my case I skip call `PromClient.collectDefaultMetrics()` and collect only custom metrics

**Comment by SimenB** [comment]
https://github.com/siimon/prom-client/releases/tag/v15.1.2
