### ISSUE TITLE
No error is raised if pushGateway server returned a 400 or 500

### ISSUE THREAD

**Issue by kdeberk** [siimon/prom-client#579]
Using the `Pushgateway` we noticed that the gravel gateway server ([this one](https://github.com/sinkingpoint/prometheus-gravel-gateway)) can sometimes reject our `POST`, `PUT` or `DELETE` request  and return a `400` (or sometimes even `500`). If that happens, then the `pushAdd`, `push`, and `delete` calls do not throw an exception. This prevents us from noticing the issue.

**Comment by kdeberk** [comment]
I've added a PR to raise an error if the gateserver returned a `>= 400` status code.

https://github.com/siimon/prom-client/pull/578

**Comment by zbjornson** [comment]
Fixed in #578, thanks for the contrib!
