### ISSUE TITLE
New metrics not created unless updated at least once

### ISSUE THREAD

**Issue by raresgmihalcea** [siimon/prom-client#580]
I'm not sure if this is supposed to be the intended behavior, but a _new_ metric only shows up after its first update.

For example, given the following counter:
```
const failedRequestCounter = new Counter({
  name: 'request_failed_total',
  help: 'The amount of failed requests',
  labelNames: ['id'],
});
```
Pushed by the following function:
```
 const updateMetrics = async () => {
 const gateway = new Pushgateway(PUSHGATEWAY_URL, register);
 await gateway.pushAdd({ jobName: 'job-name' });
 }
```
I would expect to find the following in `pushGatewayURL/metrics` after successfully calling `updateMetrics()`:
```
# HELP request_failed_total The amount of failed requests

# TYPE request_failed_total counter

request_failed_total 0.0
```

The metric will become visible only after a request fails and `failedRequestCounter.inc()` is called.

**Comment by raresgmihalcea** [comment]
A simple workaround is to increment all counters with 0. As I've said before, I am not sure if this should be the default behavior and since there is a simple way to achieve this, I'm going to close the issue

**Comment by SimenB** [comment]
Yeah, I think this is expected. We have no label values to enter
