### ISSUE TITLE
How can I attach an Authentication header to HTTP requests? 

### ISSUE THREAD

**Issue by ryanhugh** [siimon/prom-client#581]
I'm trying to send metrics to the Grafana cloud. It requires a Authorization: Bearer header: 

```
curl -X  POST -H  "Authorization: Bearer $API_KEY" -H  "Content-Type: text/plain" "$URL" -d "test,bar_label=abc,source=grafana_cloud_docs metric=43" 
```

How can I attach this header with this library?

**Comment by starriv** [comment]
Do you have any solution? I also want to know how to do it

**Comment by ryanhugh** [comment]
I did not. I ended up not using prometheus.

**Comment by starriv** [comment]
About this issue, I figured out yesterday that pushing to grafana cloud is not the right way.

This function was developed for https://github.com/prometheus/pushgateway and does not work as we imagined
