### ISSUE TITLE
defaultMetrics.metricsList not exported correctly under type definitions?

### ISSUE THREAD

**Issue by SathyaBhat** [siimon/prom-client#583]
The docs mention that we can inspect the default metrics list by the following way:

> You can get the full list of metrics by inspecting `client.collectDefaultMetrics.metricsList.`

And this works when using CommonJS require

```js

const client = require('prom-client');
console.log(client.collectDefaultMetrics.metricsList);
```

result: 

```bash 

 node index.js
[
  'processCpuTotal',
  'processStartTime',
  'osMemoryHeap',
  'processOpenFileDescriptors',
  'processMaxFileDescriptors',
  'eventLoopLag',
  'processResources',
  'processHandles',
  'processRequests',
  'heapSizeAndUsed',
  'heapSpacesSizeAndUsed',
  'version',
  'gc'
]

```

However, the type definition of this doesn't seem right, since it is defined as an interface 

```typescript
export interface defaultMetrics {
	/**
	 * All available default metrics
	 */
	metricsList: string[];
}
```

and I need to declare it? Which is not what I want. Am I doing something wrong here?

**Comment by zbjornson** [comment]
Thanks, just a typing bug. Fixed in the above commit, will be in the next release.
