### ISSUE TITLE
Getting encoding error while trying to publish SUMMARY type metrics

### ISSUE THREAD

**Issue by ShlokWingman** [siimon/prom-client#589]
While trying to push metrics to pushgateway, I'm getting this error:

```
An error has occurred during metrics encoding:

MetricFamily has no metrics: name:"<metric_name>" help:"<metric_help>" type:SUMMARY
```

This happened alternate times e.g. first time I tried to push metrics I got this error on pushgateway but the second time when I tried to push new metrics from the same pod I got the previous metrics also with it.

What are the things I can try to debug and fix this?

**Comment by zbjornson** [comment]
Can you provide the relevant part of your code that reproduces the issue please?
