### ISSUE TITLE
How do I disable default metrics collection?

### ISSUE THREAD

**Issue by omerlh** [siimon/prom-client#603]
Looking at [express-prom-bundle](https://www.npmjs.com/package/express-prom-bundle#other-options) docs, disabling default collector is possible by setting:
```javascript
{
        collectDefaultMetrics: {},
}
```

But this is not working, and when looking at the code, I didn't saw a way to disable it. Searching for issues I found an old one (#44), that might do the trick but it looks kinda clunky / hucky. Is this still the only way to achieve that? The default metrics creates a lot of load on Prometheus when having many small services.

**Comment by zbjornson** [comment]
Default metrics are opt-in with `client.collectDefaultMetrics()`. As long as you don't call that, they won't get collected. If that doesn't work, this is probably a question for express-prom-bundle.

**Comment by omerlh** [comment]
Thanks!
