### ISSUE TITLE
Cannot enable Exemplars on collectDefaultMetrics()

### ISSUE THREAD

**Issue by vmignot** [siimon/prom-client#605]
I'm trying to enable exemplars on `collectDefaultMetrics`, but without much success.

Here is a snippet of code (v15.1.0) :
```ts
  import { register, collectDefaultMetrics } from 'prom-client';
  register.setContentType('application/openmetrics-text; version=1.0.0; charset=utf-8');
  collectDefaultMetrics();
```
Then when requesting my `/metrics`, no exemplars are set on my counters or histo
```
~# curl localhost/metrics
# HELP process_cpu_user_seconds Total user CPU time spent in seconds.
# TYPE process_cpu_user_seconds counter
process_cpu_user_seconds_total{} 7.950018
# HELP process_cpu_system_seconds Total system CPU time spent in seconds.
# TYPE process_cpu_system_seconds counter
process_cpu_system_seconds_total{} 1.1639300000000001
[....]
# EOF

```

Do I have to inject the `traceId` and `spanId` myself at some point?
Am I missing something, or do I have to use a custom registry for that purpose?

Thanks!

**Comment by SimenB** [comment]
Default metrics don't really have exemplars as they're never e.g. request bound - so there are no trace or span IDs to use. I _think_ this is expected?

**Comment by vmignot** [comment]
> Default metrics don't really have exemplars as they're never e.g. request bound - so there are no trace or span IDs to use. I _think_ this is expected?

Ho, I see, my bad in that case!
