### ISSUE TITLE
Is prom-client open source free to use License 

### ISSUE THREAD

**Issue by Jagadishsy** [siimon/prom-client#612]
Hi 
In our environment we have node.js application which has been built using MIT license. When I was trying to install prom-client to monitor stats of node.js application I saw prom-client license shows it's built on apache 2.0.

My query is can I use this prom-client which is built using apache2.0 can I use this to monitor node.js application built using MIT license.

Will this be issue in licensing ??

**Comment by SimenB** [comment]
As long as you don't modify and distribute, there are no real differences between the licenses for consumers.

For more details, I suggest you google the difference between the licenses.

(IANAL)
