### ISSUE TITLE
How to change registry type to OpenMetrics?

### ISSUE THREAD

**Issue by zigazajc007** [siimon/prom-client#614]
<img width="866" alt="image" src="https://github.com/siimon/prom-client/assets/44822563/7ed53f5d-b3a2-41bc-8955-df64ca290022">

<img width="1016" alt="image" src="https://github.com/siimon/prom-client/assets/44822563/2bb55110-aaca-4acc-9db7-1b9667d1c24d">

<img width="1136" alt="image" src="https://github.com/siimon/prom-client/assets/44822563/4727c2b2-2c1c-4620-b8eb-ca4dcc9a685c">

**Comment by jamesla** [comment]
Did you solve this?

**Comment by zigazajc007** [comment]
> @zigazajc007 Did you solve this?

I didn't.

**Comment by SimenB** [comment]
The static prop is just missing from the types, it works at runtime. You can also do `Prometheus.openMetricsContentType` which _is_ present in types

**Comment by SimenB** [comment]
https://github.com/siimon/prom-client/releases/tag/v15.1.2

**Comment by jamesla** [comment]
Thanks @SimenB but this is actualy still not working with the latest version

```
error TS2345: Argument of type '"application/openmetrics-text; version=1.0.0; charset=utf-8"' is not assignable to parameter of type '"text/plain; version=0.0.4; charset=utf-8"'.
```

**Comment by SimenB** [comment]
Hah. Still only a type error, so a `@ts-ignore` should do it.

Happy to take a PR fixing it properly
