### ISSUE TITLE
Counters should be created by `.inc(0)`

### ISSUE THREAD

**Issue by leonerd** [siimon/prom-client#63]
It's a common pattern in metrics instrumentation to report counters across some set of named states as labels. It's also common to initialise them all to zeroes initially, so that the first increment is noticed by prometheus and on graphs. Otherwise, prometheus' `rate()` function fails to see the jump from not-existing to 1, and hence the first occurrence of every event never appears on a graph. This can matter enormously for rare events.

For example, I have some code that performs:

    var counter = new client.Counter(..., ["state"]);
    STATES.forEach((state) => counter.inc({state: state}, 0));

With the older `prometheus-client` library I migrated away from, this would initialise every counter to zero in output. Using `prom-client` this doesn't happen, and the first occurrence goes unnoticed.

**Comment by siimon** [comment]
I agree, we don't handle inc with 0's in an optimal way - working around this seems easy enough with just inc with 1 when you initialise it right? Ofc then the value of the counter won't match the number of times the event occurred but the rate will be correct.

I'll have a look on it abit later

**Comment by disjunction** [comment]
+1
I was using a Counter for cron.job running daily. Current implementation misses first event when using `increase(...)` in the query
