### ISSUE TITLE
Uncaught error when tracking heap usage

### ISSUE THREAD

**Issue by Kegsay** [siimon/prom-client#67]
Even though Node do not document it, this [line](https://github.com/siimon/prom-client/blob/bf9d7880f13a22ec5ffee77ba83fe8b405540fa3/lib/metrics/heapSizeAndUsed.js#L18) can throw with:

```
Error: EMFILE: too many open files, uv_resident_set_memory
    at Error (native)
    at /...../node_modules/prom-client/lib/metrics/heapSizeAndUsed.js:18:26
    at /...../node_modules/prom-client/lib/defaultMetrics.js:49:11
    at Array.forEach (native)
    at Timeout.updateAllMetrics [as _onTimeout] (/...../node_modules/prom-client/lib/defaultMetrics.js:48:16)
    at ontimeout (timers.js:365:14)
    at Timer.unrefdHandle (timers.js:466:3)
```

It would be polite if `prom-client` could catch this.

**Comment by sam-github** [comment]
Note that it will throw for any reason that http://docs.libuv.org/en/v1.x/misc.html#c.uv_resident_set_memory returns an error. For example `/proc` fs is not mounted, or whatever platform specific errors might occur when gathering the rss.
