### ISSUE TITLE
Gauge.startTimer should have configurable unit

### ISSUE THREAD

**Issue by ozankaya** [siimon/prom-client#7]
As a client I would like to be able to set the precision/unit of the time measured. For instance microsecond level.

**Comment by siimon** [comment]
This is not encouraged by the prometheus team, see https://docs.google.com/document/d/1zHwWVigeAITbaAp6BR4uCByRJH7rtTv4ve6SsoEXJ_Q/edit?usp=sharing

So I'll close this one
