### ISSUE TITLE
Self-signed https pushgateway

### ISSUE THREAD

**Issue by davidchua** [siimon/prom-client#73]
Is it possible to trigger a skip ssl cert verification for `pushgateway` connections?

I have a pushgateway that lives on a self-signed https endpoint but I'm getting certificate errors when its trying access the pushgateway.

**Comment by siimon** [comment]
Yeah it should not be that much of a problem - when you create a pushgateway we could add a second argument that is an option object that could have that setting.

**Comment by siimon** [comment]
It's now possible to extend the pushgateway with options available from nodes http/https modules - so to solve your issue setup your pushgateway like this: 

```javascript
i = new Pushgateway('https://192.168.0.1:9091', { 'rejectUnauthorized': true });
```

Can you please verify that this works for you?

**Comment by davidchua** [comment]
Thanks @siimon!

It works perfectly!
