### ISSUE TITLE
looking for simple example

### ISSUE THREAD

**Issue by vnugent** [siimon/prom-client#76]
I'm relatively new to node.js and have trouble understanding the example particularly how to create a simple 'hello world' app.
https://github.com/siimon/prom-client/blob/master/example/server.js#L5
 `var register = require('../lib/register');`

It seems I need to clone prom-client repo in order to get the example to work. If I consume prom-client as a npm module how would  I use prom client with express? Thanks.
```
var client = require('prom-client');

// express
```

**Comment by siimon** [comment]
The example could be abit clearer on that point. The register is exposed in index.js - so in your code you should just replace the register line with

```javascript 
let register = require("prom-client").register;
```

I'll try to update the example when I get the time!
