### ISSUE TITLE
How to push metrics pushgateway

### ISSUE THREAD

**Issue by JuoCode** [siimon/prom-client#79]
Is there a function like [client_python](https://github.com/prometheus/client_python#exporting-to-a-pushgateway)'s `push_to_gateway` used to export all metrics data to Pushgateway?

**Comment by siimon** [comment]
I'm not that familiar with the Python client, but the equivalent in prom-client should be the push function

**Comment by JuoCode** [comment]
```
gateway.push({ jobName: 'job-1', groupings: {...} })
const metricsJSON = register. getMetricsAsJSON()
```
How can i push `metricsJSON` to Pushgateway server via `gateway.push` method?

**Comment by siimon** [comment]
Not sure I follow you, when you invoke the push function, prom-client pushes all metrics that's in the register. There is no need to extract all the metrics as JSON in this case

**Comment by JuoCode** [comment]
Sorry, I thought it need passing metrics json into push method...
Thank you!

**Comment by vance** [comment]
when pushing, does it continue to push at the timeout interval without further interaction, or is this a one time push and you have to call it again with a timer?
