### ISSUE TITLE
Aggregate metrics in multiprocess mode

### ISSUE THREAD

**Issue by tommiv** [siimon/prom-client#80]
So we use pm2 to run nodes "cluster" in fork mode to fully utilize server cpu cores. This means that every node.js instance can use prom-client to generate the metrics of its own process, but we need one more step to aggregate metrics from every node to a single metric. Is there some solutions with prom-client or I need an external aggregator for this (is there any in the wild then?). Sorry it this is a wrong place to ask this question.

**Comment by siimon** [comment]
Prom-client does not support that, and I don't think it ever will. 

LBest would probably be as you said, to build something on top of prom-client that aggregates and exposes them. But it has some challenges, maybe you would like to know stats for a specific node? That data will be lost when aggregated etc!

**Comment by tommiv** [comment]
Thanks for your answer, I will try some workarounds.
> That data will be lost when aggregated
this is true, but we probably ok with this. Since we can't collect data from each process with standard pull model, we need some trade-offs.

**Comment by saqibarfeen** [comment]
With the help of [this](https://gist.github.com/yekver/34c9d41c1c4ea478151574ea539e9953) and [this](https://github.com/slanatech/swaggerstats.io/blob/master/docs/guide/prometheus.md)
I was able to achieve exactly what you are asking.  See my [gist](https://gist.github.com/saqibarfeen/8bc729ade1c1b17fad764d924e64af32)
(in case someone else reads this)
