### ISSUE TITLE
Way to provide labels for default metrics?

### ISSUE THREAD

**Issue by goofballLogic** [siimon/prom-client#83]
I can't find a way (from reading the code and readme) to add labels to the default metrics. This is important with regard to production deployment so that e.g. process id can be associated without forcing this data to be a grouping.

This is particularly important when needing to override the "instance" label (for pushgateway instances)

**Comment by SimenB** [comment]
This is not currently possible, no. I like the idea though, but how do you imagine the API would look like?

**Comment by siimon** [comment]
I agree, as long as we keep the API simple I don't mind this, but I think that will be the hardest part. 

I guess you could send in a function that returns an object with key values which is the label key and values. But I guess some validation is needed, since it could only be one level deep and not contain any functions etc..

**Comment by SkeLLLa** [comment]
I also need some kind of such functionality. @siimon probably it could solve the problem if there will be some way to set "default" labels for all metrics. E.g. setting them in some kind of constructor:
```js
var pc = require('prom-client')({
  defaultLabels: {
    hostname: 'host1.example.com',
    zone: 'us-east'
  }
})
```
and all those labels should be passed to both default metrics constructors and custom. So:
```js
new Gauge(PROCESS_HEAP , 'Process heap size in bytes.')
```
should become:
```js
new Gauge(PROCESS_HEAP , 'Process heap size in bytes.', Object.keys(defaultLabels))
```
and custom metrics:
```js
var customLabels = ['label1', 'label2'];
new Gauge('custom_metric' , 'description', Object.keys(defaultLabels).concat(customLabels))
```

**Comment by bspradling8** [comment]
+1 for this request.

**Comment by SkeLLLa** [comment]
I've found some kind of workaround for me. As I use consul for registering my services I was able to add default labels through counul tags and parse them with promise consul meta information, but anyway if someone don't have such options there should be some way to do this through this lib.

**Comment by SkeLLLa** [comment]
@goofballLogic, @bspradling8 I've made some "progress" according to this issue. The result you could find here: https://gitlab.com/prometheus-nodejs. There are separate plugins that could be initialized separately (see readmes). During initialization you could override metric name, description, add custom labels or disable some metrics. 

I'm currently in progress of porting all existing metrics into such separate plugins. Also there will be some new plugins like universal http/tcp stats plugin. Some metric names have change, so pay attention to it or just use override option to make them look like current. Also I plan to create some meta package or just helper that could start all those plugins with one or two function calls, but for now they should be started separately.

**Comment by SimenB** [comment]
This is done in #137.
