### ISSUE TITLE
Expose the right content-type as a constant

### ISSUE THREAD

**Issue by crccheck** [siimon/prom-client#84]
In the [official Prometheus Python client](https://github.com/prometheus/client_python), they expose a constant for the right content-type header and it's tied to the library. That would be nice in this package too.

`client_python`:
```
>>> from prometheus_client import CONTENT_TYPE_LATEST
>>> CONTENT_TYPE_LATEST
'text/plain; version=0.0.4; charset=utf-8'
```
from https://github.com/prometheus/client_python/blob/ce5542bd8be2944a1898e9ac3d6e112662153ea4/prometheus_client/exposition.py#L29

**Comment by SimenB** [comment]
Huh, version as well. Nice.
