### ISSUE TITLE
Add "external" memory usage

### ISSUE THREAD

**Issue by SkeLLLa** [siimon/prom-client#88]
Hello. Starting from node v7.2.0 `external` filed was added ([link](https://nodejs.org/api/process.html#process_process_memoryusage)) to output of `process.memoryUsage()`. For most people it probably will not be interesting, but it could help sometimes to find out issues when your app dealing with intensive i/o operations by tracking amount of memory used for bound C++ objects.

I can make a PR, but I don't know where it should be placed, because it's present on all OS, but here we have separate module for measuring linux memory usage which doesn't call `process.memoryUsage`. So as this metric could be not so popular it can be moved to separate module to provide ability for users to disable it. On the other hand adding it to existing module could save additional `process.memoryUsage` call. So basically the question is do we really need this as default metric and if so, where it should be placed?

**Comment by SimenB** [comment]
The Linux one could be expanded to include information from `process.memoryUsage` as well.

**Comment by SkeLLLa** [comment]
@SimenB, yes, basically we can add `process.memoryUsage` to linux variant, but what values should we take, for example, as `process_heap_bytes`, one from linux proc stats or from output of `memoryUsage` function?

**Comment by SimenB** [comment]
Do they differ?

**Comment by SkeLLLa** [comment]
Yep. Up to 10 times :)/ It seems that linux `process_heap_bytes` is value a bit less than virtual bytes. But `process.memoryUsage` return actual values used by code, variables, etc.

**Comment by SimenB** [comment]
I'm more inclined to trust what Linux says is used rather than what V8 says, but such a large difference might indicate there's a bug somewhere

**Comment by SkeLLLa** [comment]
@SimenB I don't think that linux version of heap usage can show something, because it's value is close to virtual memory size and much bigger than resident set. I think it shows also allocated for process, but still not used memory just as virtual one (virtual = rss + swap).

**Comment by SimenB** [comment]
Hmm, good point!

**Comment by SkeLLLa** [comment]
@SimenB according to stuff that I've read `VmData` usually never shrinks and even when process heap is freed. Memory allocators just keep the freed memory for future allocations.

**Comment by SimenB** [comment]
So the process itself keeps it in reserve even if the application has dropped it?

**Comment by SkeLLLa** [comment]
@SimenB, as I understood - yes.

**Comment by SimenB** [comment]
Then my vote is to keep it like it is, but add `process.memoryUsage()` behind the `nodejs_` prefix. So like `nodejs_process_rss` etc. WYDT?

**Comment by SkeLLLa** [comment]
@SimenB sounds good. Also I think it would be better if we move [platform check](https://github.com/siimon/prom-client/blob/master/lib/metrics/osMemoryHeap.js#L23)  to `osMemoryHeapLinux.js` file and will treat `osMemoryHeapLinux` just as separate metric, and `osMemoryHeap.js` as universal metric for all platforms that will contain 2 gauges: for rss and external (if node supports this value).

**Comment by SimenB** [comment]
I'm down with that 😄

**Comment by SkeLLLa** [comment]
@SimenB Ok :). Anyway this issue is about adding external memory metric. So I've added it into both linux and non-linux variant. Probably later I'll provide some kind of refactoring proposition with code, to make it easier to decide :).

**Comment by siimon** [comment]
Thanks! Closing this since it's fixed in #94 and released in v8.0.0
