### ISSUE TITLE
Counter Validation Design Question

### ISSUE THREAD

**Issue by therynamo** [siimon/prom-client#95]
I was assigning some values to the `Counter` prototype, and using the metric name `200`, this of course is a number, which violates [this regex](https://github.com/siimon/prom-client/blob/master/lib/validation.js#L4). 

My question is, if I was looking to record status codes of the name `200` with a label of `statusCode`, would you see this as still acceptable? Or would you request I flip them and use the status codes for labels? If the latter, what challenges do you see the former providing from a design prospective?

Thanks for your time!

Theryn

**Comment by therynamo** [comment]
Further exploration leads me to see that any `number` as a value, will not suffice. 

E.g.:
```js
// Number as metric name
new Prometheus.Counter('200', 'Status Code 200', ['statusCode']);

// Number as label
new Prometheus.Counter('statusCode', 'Status Code 200', ['200']);
```

**Comment by siimon** [comment]
Not sure I get what you mean. A better approach would be to name the metric to something that makes sense in what context it's used. For example 

serviceX_requests_total

And then use the status code as a label to that metric.

Just having a metric named statusCode doesn't make much sense in a broader context.

**Comment by therynamo** [comment]
Thats a good point. Thank you for your suggestion!
