### ISSUE TITLE
Optionally serve metrics in protocol buffer format?

### ISSUE THREAD

**Issue by snarlysodboxer** [siimon/prom-client#96]
Thank for the great library!

Would you be interested in a pull request related to serving metrics to prometheus in the protocol buffer format?

My thought was to create a new function in `lib/register.js` named something like `getMetricsAsProtobuf()` which returns a buffer containing the 32-bit varint-encoded record length-delimited protocol buffer messages of type `io.prometheus.client.MetricFamily` which prometheus expects. This buffer could be returned in the body of an HTTP response using something like Express or Koa.

There would be one added dependency, [protobufjs](https://www.npmjs.com/package/protobufjs).

The only issue is, you guys internally store the metrics in a format that is not compliant with prometheus' [metrics.proto](https://github.com/prometheus/client_model/blob/proto3/metrics.proto) messages, so either A), a conversion function is required, or B), we consider updating prom-client to internally store metrics as `MetricFamily` compliant objects. (E.G. for `metric.type`, we store `0` instead of `counter`, etc.)

Here's the conversion function we're using, it would be nice not to have to do this. It returns an array of metric objects from which we create protobuf messages using protobufjs's generated code's `MetricFamily.fromObject(metric)` function. (Note: support for Summary and Histogram is unfinished.)

```node
// Convert prom-client metric objects to `io.prometheus.client.MetricFamily` compliant objects
function convertMetrics() {
    let convertedMetrics = []
    for (let metricFamily of prom.getMetricsAsJSON()) {
        let newMetricFamily = {}
        newMetricFamily.name = metricFamily.name
        newMetricFamily.help = metricFamily.help
        let newMetrics = []
        for (let metric of metricFamily.values) {
            let newMetric = {}
            let newLabels = []
            Object.keys(metric.labels).forEach(function (key) {
                if (metric.labels[key].toString() != null)
                    newLabels.push({ "name": key, "value": metric.labels[key].toString() });
            });
            newMetric.label = newLabels;
            switch (metricFamily.type) {
                case "counter":
                    newMetricFamily.type = 0;
                    newMetric.counter = { "value": metric.value };
                    break;
                case "gauge":
                    newMetricFamily.type = 1;
                    newMetric.gauge = { "value": metric.value };
                    break;
                case "summary":
                    newMetricFamily.type = 2;
                    // TODO
                    break;
                case "histogram":
                    newMetricFamily.type = 4;
                    // TODO
                    break;
            }
            // TODO timestamp_ms is not supported in prom-client? (confirm or contribute)
            // newMetric.timestamp_ms = metric.timestamp_ms;
            newMetrics.push(newMetric);
        }
        newMetricFamily.metric = newMetrics
        convertedMetrics.push(newMetricFamily);
    }
    return convertedMetrics;
}
```

I've written code that successfully sends the protobuf messages to prometheus, I'd like to share it, but the conversion part feels hacky. Thoughts?

**Comment by siimon** [comment]
I'd happily merge a PR that adds protobuf support!

Is the type and labels properties the only thing that's not compliant?

IMO I think a conversion function would be the best, but you could probably add a property in each metric type to get the types int representation. With the labels you probably add a function in the utils file - or the even better, create a new file that does all protobuf handling and place the function there as well. This would make it feel less hacky. 

Did it make any sense? :)

**Comment by SimenB** [comment]
This would be really nice!
Timestamp is #69 btw (the todo in your sample code)

**Comment by snarlysodboxer** [comment]
Makes sense. Thanks guys, I'll see what I can do. :)

**Comment by siimon** [comment]
Yeah, I'll try and polish up and merge #69 this week

**Comment by siimon** [comment]
@snarlysodboxer please be aware of what's happening in #100, will probably affect you if you haven't begun yet!

**Comment by snarlysodboxer** [comment]
@siimon Thanks for the heads up! I haven't had time to do much yet. I was hoping to do it this coming week, but I think I'll wait until #100 settles.

**Comment by SimenB** [comment]
@snarlysodboxer #100 has been merged and released

**Comment by snarlysodboxer** [comment]
Thanks! I should be able to get to very soon.

**Comment by snarlysodboxer** [comment]
Hey guys, almost finished, looking for feedback: [#108](https://github.com/siimon/prom-client/pull/108).

**Comment by brian-brazil** [comment]
Prometheus 2.x does not support proto, so this can be closed.

**Comment by Bruno-DaSilva** [comment]
Reintroduced! https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#protobuf-format
